// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LoadingPage
void ui_LoadingPage_screen_init(void);
void ui_event_LoadingPage(lv_event_t * e);
lv_obj_t * ui_LoadingPage;
lv_obj_t * ui_Spinner;
lv_obj_t * ui_Loading;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Title1;
lv_obj_t * ui_Title2;
lv_obj_t * ui_Title3;
lv_obj_t * ui_Version;
lv_obj_t * ui_Process;


// SCREEN: ui_LoginPage
void ui_LoginPage_screen_init(void);
void ui_event_LoginPage(lv_event_t * e);
lv_obj_t * ui_LoginPage;
lv_obj_t * ui_LogoContainer;
lv_obj_t * ui_Polipharm;
lv_obj_t * ui_DateTimePanel;
lv_obj_t * ui_HoursPanel;
lv_obj_t * ui_Hours;
lv_obj_t * ui_HM;
lv_obj_t * ui_MinutesPanel;
lv_obj_t * ui_Minutes;
lv_obj_t * ui_MS;
lv_obj_t * ui_SecondsPanel;
lv_obj_t * ui_Seconds;
lv_obj_t * ui_DatePanel;
lv_obj_t * ui_Date;
lv_obj_t * ui_MsgRfidScan;
lv_obj_t * ui_ErrMsgRfidScan;
lv_obj_t * ui_LoginPanel;
lv_obj_t * ui_TitlePanel;
lv_obj_t * ui_LoginTitle;
lv_obj_t * ui_ScaleIMG;
lv_obj_t * ui_RfidPanel;
lv_obj_t * ui_RFID;
lv_obj_t * ui_SettingBtn;


// SCREEN: ui_WeighingPage
void ui_WeighingPage_screen_init(void);
void ui_event_WeighingPage(lv_event_t * e);
lv_obj_t * ui_WeighingPage;
lv_obj_t * ui_WeightPanel1;
lv_obj_t * ui_TitleWeight1;
lv_obj_t * ui_Weight1;
lv_obj_t * ui_WeightPanel2;
lv_obj_t * ui_TitleWeight2;
lv_obj_t * ui_Weight2;
lv_obj_t * ui_AveragePanel;
lv_obj_t * ui_TitleAverage;
lv_obj_t * ui_Average;
lv_obj_t * ui_WeightSetMainPanel;
lv_obj_t * ui_ProductContainer;
lv_obj_t * ui_ProductLabel;
lv_obj_t * ui_SlaveProductContainer;
lv_obj_t * ui_ProductName;
lv_obj_t * ui_LotContainer;
lv_obj_t * ui_LotLabel;
lv_obj_t * ui_SlaveLotContainer;
lv_obj_t * ui_LotNumber;
lv_obj_t * ui_BalanceContainer;
lv_obj_t * ui_BalanceLabel;
lv_obj_t * ui_SlaveBalanceContainer;
lv_obj_t * ui_BalanceID;
lv_obj_t * ui_TabletIDContainer;
lv_obj_t * ui_TabletIDLabel;
lv_obj_t * ui_SlaveTabletIDContainer;
lv_obj_t * ui_TabletID;
lv_obj_t * ui_Weight10sContainer;
lv_obj_t * ui_Weight10sLabel;
lv_obj_t * ui_SlaveWeight10sContainer;
lv_obj_t * ui_Weight10s;
lv_obj_t * ui_Weight10sUnit;
lv_obj_t * ui_Weight10sPerContainer;
lv_obj_t * ui_Weight10sPerLabel;
lv_obj_t * ui_SlaveWeight10sPerContainer;
lv_obj_t * ui_Weight10sPer;
lv_obj_t * ui_Weight10sPerUnit;
lv_obj_t * ui_MeanWeightInhouseContainer;
lv_obj_t * ui_MeanWeightInhouseLabel;
lv_obj_t * ui_SlaveMeanWeightInhouseContainer;
lv_obj_t * ui_WeightInhouseMin;
lv_obj_t * ui_dash;
lv_obj_t * ui_WeightInhouseMax;
lv_obj_t * ui_MeanWeightInhouseUnit;
lv_obj_t * ui_MeanWeightREGContainer;
lv_obj_t * ui_MeanWeightREGLabel;
lv_obj_t * ui_SlaveMeanWeightREGContainer;
lv_obj_t * ui_WeightRegMin;
lv_obj_t * ui_dash2;
lv_obj_t * ui_WeightRegMax;
lv_obj_t * ui_MeanWeightREGUnit;
lv_obj_t * ui_ThicknessContainer;
lv_obj_t * ui_ThicknessLabel;
lv_obj_t * ui_SlaveThicknessContainer;
lv_obj_t * ui_ThicknessMin;
lv_obj_t * ui_ThicknessMax;
lv_obj_t * ui_dash3;
lv_obj_t * ui_MeanWeightREGUnit1;
lv_obj_t * ui_UpdateSettingBtn;
lv_obj_t * ui_UpdateSettingLabel;
lv_obj_t * ui_ClearSettingBtn;
lv_obj_t * ui_ClearSettingLabel;


// SCREEN: ui_ThicknessPage
void ui_ThicknessPage_screen_init(void);
void ui_event_ThicknessPage(lv_event_t * e);
lv_obj_t * ui_ThicknessPage;
lv_obj_t * ui_ThicknessMainPanel;
lv_obj_t * ui_ThicknessA;
lv_obj_t * ui_ThicknessPanel1;
lv_obj_t * ui_ThicknessLabel1;
lv_obj_t * ui_Thickness1;
lv_obj_t * ui_ThicknessPanel2;
lv_obj_t * ui_ThicknessLabel2;
lv_obj_t * ui_Thickness2;
lv_obj_t * ui_ThicknessPanel3;
lv_obj_t * ui_ThicknessLabel3;
lv_obj_t * ui_Thickness3;
lv_obj_t * ui_ThicknessPanel4;
lv_obj_t * ui_ThicknessLabel4;
lv_obj_t * ui_Thickness4;
lv_obj_t * ui_ThicknessPanel5;
lv_obj_t * ui_ThicknessLabel5;
lv_obj_t * ui_Thickness5;
lv_obj_t * ui_ThicknessB;
lv_obj_t * ui_ThicknessPanel6;
lv_obj_t * ui_ThicknessLabel6;
lv_obj_t * ui_Thickness6;
lv_obj_t * ui_ThicknessPanel7;
lv_obj_t * ui_ThicknessLabel7;
lv_obj_t * ui_Thickness7;
lv_obj_t * ui_ThicknessPanel8;
lv_obj_t * ui_ThicknessLabel8;
lv_obj_t * ui_Thickness8;
lv_obj_t * ui_ThicknessPanel9;
lv_obj_t * ui_ThicknessLabel9;
lv_obj_t * ui_Thickness9;
lv_obj_t * ui_ThicknessPanel10;
lv_obj_t * ui_ThicknessLabel10;
lv_obj_t * ui_Thickness10;
lv_obj_t * ui_CancelBtn;
lv_obj_t * ui_Cancel;
lv_obj_t * ui_ConfirmBtn;
lv_obj_t * ui_Confirm;
lv_obj_t * ui_KeyboardPanel;
lv_obj_t * ui_ThicknessKeyboard;
lv_obj_t * ui_ThicknessValue;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_ThicknessTitleLabel;


// SCREEN: ui_TabletCharacteristicsPage
void ui_TabletCharacteristicsPage_screen_init(void);
void ui_event_TabletCharacteristicsPage(lv_event_t * e);
lv_obj_t * ui_TabletCharacteristicsPage;
lv_obj_t * ui_TabletCharacteristicsPanel;
lv_obj_t * ui_TabletCharacteristics;
lv_obj_t * ui_NomalPillsBtn;
lv_obj_t * ui_NomalLabel;
lv_obj_t * ui_NotgoodPillsBtn;
lv_obj_t * ui_NotgoodLabel;
lv_obj_t * ui_PillsTopIMG;
lv_obj_t * ui_PillsBelowIMG;
lv_obj_t * ui_PillsTopLabel;
lv_obj_t * ui_PillsBelowLabel;


// SCREEN: ui_SummaryPage
void ui_SummaryPage_screen_init(void);
void ui_event_SummaryPage(lv_event_t * e);
lv_obj_t * ui_SummaryPage;
lv_obj_t * ui_SummaryTitlePanel;
lv_obj_t * ui_SummaryTitle;
lv_obj_t * ui_SummaryW1Panel;
lv_obj_t * ui_TitleSumW1;
lv_obj_t * ui_SumW1;
lv_obj_t * ui_SummaryW2Panel;
lv_obj_t * ui_TitleSumW2;
lv_obj_t * ui_SumW2;
lv_obj_t * ui_SummaryAveragePanel;
lv_obj_t * ui_TitleSumAverage;
lv_obj_t * ui_SumAverage;
lv_obj_t * ui_SummaryPercent;
lv_obj_t * ui_TitleSumPercent;
lv_obj_t * ui_SumPercent;
lv_obj_t * ui_SummaryTkPanel;
lv_obj_t * ui_MinTkPanel;
lv_obj_t * ui_TitleMinTk;
lv_obj_t * ui_MinTk;
lv_obj_t * ui_MaxTkPanel;
lv_obj_t * ui_TitleMaxTk;
lv_obj_t * ui_MaxTk;
lv_obj_t * ui_SummaryTkCon1;
lv_obj_t * ui_ThicknessPanel11;
lv_obj_t * ui_ThicknessLabel11;
lv_obj_t * ui_Thickness11;
lv_obj_t * ui_ThicknessPanel12;
lv_obj_t * ui_ThicknessLabel12;
lv_obj_t * ui_Thickness12;
lv_obj_t * ui_ThicknessPanel13;
lv_obj_t * ui_ThicknessLabel13;
lv_obj_t * ui_Thickness13;
lv_obj_t * ui_ThicknessPanel14;
lv_obj_t * ui_ThicknessLabel14;
lv_obj_t * ui_Thickness14;
lv_obj_t * ui_SummaryTkCon2;
lv_obj_t * ui_ThicknessPanel15;
lv_obj_t * ui_ThicknessLabel15;
lv_obj_t * ui_Thickness15;
lv_obj_t * ui_ThicknessPanel16;
lv_obj_t * ui_ThicknessLabel16;
lv_obj_t * ui_Thickness16;
lv_obj_t * ui_ThicknessPanel17;
lv_obj_t * ui_ThicknessLabel17;
lv_obj_t * ui_Thickness17;
lv_obj_t * ui_ThicknessPanel18;
lv_obj_t * ui_ThicknessLabel18;
lv_obj_t * ui_Thickness18;
lv_obj_t * ui_SummaryTkCon3;
lv_obj_t * ui_ThicknessPanel21;
lv_obj_t * ui_ThicknessLabel21;
lv_obj_t * ui_Thickness21;
lv_obj_t * ui_ThicknessPanel22;
lv_obj_t * ui_ThicknessLabel22;
lv_obj_t * ui_Thickness22;
lv_obj_t * ui_SummaryEndPanel;
lv_obj_t * ui_SummaryTimeoutPanel;
lv_obj_t * ui_SummaryTimeout;
lv_obj_t * ui_SummaryEndBtn;


// SCREEN: ui_SettingPage
void ui_SettingPage_screen_init(void);
lv_obj_t * ui_SettingPage;
lv_obj_t * ui_Brightness;
lv_obj_t * ui_BrightnessLabel;
lv_obj_t * ui_Sound;
lv_obj_t * ui_SoundLabel;
void ui_event_WifiPanel(lv_event_t * e);
lv_obj_t * ui_WifiPanel;
lv_obj_t * ui_WifiScanBtn;
lv_obj_t * ui_WifiScanLabel;
lv_obj_t * ui_WifiList;
lv_obj_t * ui_WifiSignal;
lv_obj_t * ui_WifiConnectBtn;
lv_obj_t * ui_WifiConnectLabel;
void ui_event_CloseSettingBtn(lv_event_t * e);
lv_obj_t * ui_CloseSettingBtn;
lv_obj_t * ui_CloseSettingLabel;
lv_obj_t * ui_WaitingToWifi;
lv_obj_t * ui_WifiSpinner;
lv_obj_t * ui_WifiKeyboardPanel;
lv_obj_t * ui_WifiKeyboard;
lv_obj_t * ui_WifiKeboardInput;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_336342778[1] = {&ui_img_1636676910};
const lv_img_dsc_t * ui_imgset_1771410100[1] = {&ui_img_206557904};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LoadingPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoginPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LoginPage_screen_init);
    }
}
void ui_event_LoginPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeighingPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WeighingPage_screen_init);
    }
}
void ui_event_WeighingPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ThicknessPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ThicknessPage_screen_init);
    }
}
void ui_event_ThicknessPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TabletCharacteristicsPage, LV_SCR_LOAD_ANIM_NONE, 0, 0,
                          &ui_TabletCharacteristicsPage_screen_init);
    }
}
void ui_event_TabletCharacteristicsPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SummaryPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SummaryPage_screen_init);
    }
}
void ui_event_SummaryPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoadingPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LoadingPage_screen_init);
    }
}
void ui_event_WifiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WifiKeyboardPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_CloseSettingBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoginPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LoginPage_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoadingPage_screen_init();
    ui_LoginPage_screen_init();
    ui_WeighingPage_screen_init();
    ui_ThicknessPage_screen_init();
    ui_TabletCharacteristicsPage_screen_init();
    ui_SummaryPage_screen_init();
    ui_SettingPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoadingPage);
}
