// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#ifndef _WEIGHT_UI_H
#define _WEIGHT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_LoadingPage
void ui_LoadingPage_screen_init(void);
void ui_event_LoadingPage(lv_event_t * e);
extern lv_obj_t * ui_LoadingPage;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_Title2;
extern lv_obj_t * ui_Title3;
extern lv_obj_t * ui_Version;
extern lv_obj_t * ui_Process;
// SCREEN: ui_LoginPage
void ui_LoginPage_screen_init(void);
void ui_event_LoginPage(lv_event_t * e);
extern lv_obj_t * ui_LoginPage;
extern lv_obj_t * ui_LogoContainer;
extern lv_obj_t * ui_Polipharm;
extern lv_obj_t * ui_DateTimePanel;
extern lv_obj_t * ui_HoursPanel;
extern lv_obj_t * ui_Hours;
extern lv_obj_t * ui_HM;
extern lv_obj_t * ui_MinutesPanel;
extern lv_obj_t * ui_Minutes;
extern lv_obj_t * ui_MS;
extern lv_obj_t * ui_SecondsPanel;
extern lv_obj_t * ui_Seconds;
extern lv_obj_t * ui_DatePanel;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_MsgRfidScan;
extern lv_obj_t * ui_ErrMsgRfidScan;
extern lv_obj_t * ui_LoginPanel;
extern lv_obj_t * ui_TitlePanel;
extern lv_obj_t * ui_LoginTitle;
extern lv_obj_t * ui_ScaleIMG;
extern lv_obj_t * ui_RfidPanel;
extern lv_obj_t * ui_RFID;
extern lv_obj_t * ui_SettingBtn;
// SCREEN: ui_WeighingPage
void ui_WeighingPage_screen_init(void);
void ui_event_WeighingPage(lv_event_t * e);
extern lv_obj_t * ui_WeighingPage;
extern lv_obj_t * ui_WeightPanel1;
extern lv_obj_t * ui_TitleWeight1;
extern lv_obj_t * ui_Weight1;
extern lv_obj_t * ui_WeightPanel2;
extern lv_obj_t * ui_TitleWeight2;
extern lv_obj_t * ui_Weight2;
extern lv_obj_t * ui_AveragePanel;
extern lv_obj_t * ui_TitleAverage;
extern lv_obj_t * ui_Average;
extern lv_obj_t * ui_WeightSetMainPanel;
extern lv_obj_t * ui_ProductContainer;
extern lv_obj_t * ui_ProductLabel;
extern lv_obj_t * ui_SlaveProductContainer;
extern lv_obj_t * ui_ProductName;
extern lv_obj_t * ui_LotContainer;
extern lv_obj_t * ui_LotLabel;
extern lv_obj_t * ui_SlaveLotContainer;
extern lv_obj_t * ui_LotNumber;
extern lv_obj_t * ui_BalanceContainer;
extern lv_obj_t * ui_BalanceLabel;
extern lv_obj_t * ui_SlaveBalanceContainer;
extern lv_obj_t * ui_BalanceID;
extern lv_obj_t * ui_TabletIDContainer;
extern lv_obj_t * ui_TabletIDLabel;
extern lv_obj_t * ui_SlaveTabletIDContainer;
extern lv_obj_t * ui_TabletID;
extern lv_obj_t * ui_Weight10sContainer;
extern lv_obj_t * ui_Weight10sLabel;
extern lv_obj_t * ui_SlaveWeight10sContainer;
extern lv_obj_t * ui_Weight10s;
extern lv_obj_t * ui_Weight10sUnit;
extern lv_obj_t * ui_Weight10sPerContainer;
extern lv_obj_t * ui_Weight10sPerLabel;
extern lv_obj_t * ui_SlaveWeight10sPerContainer;
extern lv_obj_t * ui_Weight10sPer;
extern lv_obj_t * ui_Weight10sPerUnit;
extern lv_obj_t * ui_MeanWeightInhouseContainer;
extern lv_obj_t * ui_MeanWeightInhouseLabel;
extern lv_obj_t * ui_SlaveMeanWeightInhouseContainer;
extern lv_obj_t * ui_WeightInhouseMin;
extern lv_obj_t * ui_dash;
extern lv_obj_t * ui_WeightInhouseMax;
extern lv_obj_t * ui_MeanWeightInhouseUnit;
extern lv_obj_t * ui_MeanWeightREGContainer;
extern lv_obj_t * ui_MeanWeightREGLabel;
extern lv_obj_t * ui_SlaveMeanWeightREGContainer;
extern lv_obj_t * ui_WeightRegMin;
extern lv_obj_t * ui_dash2;
extern lv_obj_t * ui_WeightRegMax;
extern lv_obj_t * ui_MeanWeightREGUnit;
extern lv_obj_t * ui_ThicknessContainer;
extern lv_obj_t * ui_ThicknessLabel;
extern lv_obj_t * ui_SlaveThicknessContainer;
extern lv_obj_t * ui_ThicknessMin;
extern lv_obj_t * ui_ThicknessMax;
extern lv_obj_t * ui_dash3;
extern lv_obj_t * ui_MeanWeightREGUnit1;
extern lv_obj_t * ui_UpdateSettingBtn;
extern lv_obj_t * ui_UpdateSettingLabel;
extern lv_obj_t * ui_ClearSettingBtn;
extern lv_obj_t * ui_ClearSettingLabel;
// SCREEN: ui_ThicknessPage
void ui_ThicknessPage_screen_init(void);
void ui_event_ThicknessPage(lv_event_t * e);
extern lv_obj_t * ui_ThicknessPage;
extern lv_obj_t * ui_ThicknessMainPanel;
extern lv_obj_t * ui_ThicknessA;
extern lv_obj_t * ui_ThicknessPanel1;
extern lv_obj_t * ui_ThicknessLabel1;
extern lv_obj_t * ui_Thickness1;
extern lv_obj_t * ui_ThicknessPanel2;
extern lv_obj_t * ui_ThicknessLabel2;
extern lv_obj_t * ui_Thickness2;
extern lv_obj_t * ui_ThicknessPanel3;
extern lv_obj_t * ui_ThicknessLabel3;
extern lv_obj_t * ui_Thickness3;
extern lv_obj_t * ui_ThicknessPanel4;
extern lv_obj_t * ui_ThicknessLabel4;
extern lv_obj_t * ui_Thickness4;
extern lv_obj_t * ui_ThicknessPanel5;
extern lv_obj_t * ui_ThicknessLabel5;
extern lv_obj_t * ui_Thickness5;
extern lv_obj_t * ui_ThicknessB;
extern lv_obj_t * ui_ThicknessPanel6;
extern lv_obj_t * ui_ThicknessLabel6;
extern lv_obj_t * ui_Thickness6;
extern lv_obj_t * ui_ThicknessPanel7;
extern lv_obj_t * ui_ThicknessLabel7;
extern lv_obj_t * ui_Thickness7;
extern lv_obj_t * ui_ThicknessPanel8;
extern lv_obj_t * ui_ThicknessLabel8;
extern lv_obj_t * ui_Thickness8;
extern lv_obj_t * ui_ThicknessPanel9;
extern lv_obj_t * ui_ThicknessLabel9;
extern lv_obj_t * ui_Thickness9;
extern lv_obj_t * ui_ThicknessPanel10;
extern lv_obj_t * ui_ThicknessLabel10;
extern lv_obj_t * ui_Thickness10;
extern lv_obj_t * ui_CancelBtn;
extern lv_obj_t * ui_Cancel;
extern lv_obj_t * ui_ConfirmBtn;
extern lv_obj_t * ui_Confirm;
extern lv_obj_t * ui_KeyboardPanel;
extern lv_obj_t * ui_ThicknessKeyboard;
extern lv_obj_t * ui_ThicknessValue;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ThicknessTitleLabel;
// SCREEN: ui_TabletCharacteristicsPage
void ui_TabletCharacteristicsPage_screen_init(void);
void ui_event_TabletCharacteristicsPage(lv_event_t * e);
extern lv_obj_t * ui_TabletCharacteristicsPage;
extern lv_obj_t * ui_TabletCharacteristicsPanel;
extern lv_obj_t * ui_TabletCharacteristics;
extern lv_obj_t * ui_NomalPillsBtn;
extern lv_obj_t * ui_NomalLabel;
extern lv_obj_t * ui_NotgoodPillsBtn;
extern lv_obj_t * ui_NotgoodLabel;
extern lv_obj_t * ui_PillsTopIMG;
extern lv_obj_t * ui_PillsBelowIMG;
extern lv_obj_t * ui_PillsTopLabel;
extern lv_obj_t * ui_PillsBelowLabel;
// SCREEN: ui_SummaryPage
void ui_SummaryPage_screen_init(void);
void ui_event_SummaryPage(lv_event_t * e);
extern lv_obj_t * ui_SummaryPage;
extern lv_obj_t * ui_SummaryTitlePanel;
extern lv_obj_t * ui_SummaryTitle;
extern lv_obj_t * ui_SummaryW1Panel;
extern lv_obj_t * ui_TitleSumW1;
extern lv_obj_t * ui_SumW1;
extern lv_obj_t * ui_SummaryW2Panel;
extern lv_obj_t * ui_TitleSumW2;
extern lv_obj_t * ui_SumW2;
extern lv_obj_t * ui_SummaryAveragePanel;
extern lv_obj_t * ui_TitleSumAverage;
extern lv_obj_t * ui_SumAverage;
extern lv_obj_t * ui_SummaryPercent;
extern lv_obj_t * ui_TitleSumPercent;
extern lv_obj_t * ui_SumPercent;
extern lv_obj_t * ui_SummaryTkPanel;
extern lv_obj_t * ui_MinTkPanel;
extern lv_obj_t * ui_TitleMinTk;
extern lv_obj_t * ui_MinTk;
extern lv_obj_t * ui_MaxTkPanel;
extern lv_obj_t * ui_TitleMaxTk;
extern lv_obj_t * ui_MaxTk;
extern lv_obj_t * ui_SummaryTkCon1;
extern lv_obj_t * ui_ThicknessPanel11;
extern lv_obj_t * ui_ThicknessLabel11;
extern lv_obj_t * ui_Thickness11;
extern lv_obj_t * ui_ThicknessPanel12;
extern lv_obj_t * ui_ThicknessLabel12;
extern lv_obj_t * ui_Thickness12;
extern lv_obj_t * ui_ThicknessPanel13;
extern lv_obj_t * ui_ThicknessLabel13;
extern lv_obj_t * ui_Thickness13;
extern lv_obj_t * ui_ThicknessPanel14;
extern lv_obj_t * ui_ThicknessLabel14;
extern lv_obj_t * ui_Thickness14;
extern lv_obj_t * ui_SummaryTkCon2;
extern lv_obj_t * ui_ThicknessPanel15;
extern lv_obj_t * ui_ThicknessLabel15;
extern lv_obj_t * ui_Thickness15;
extern lv_obj_t * ui_ThicknessPanel16;
extern lv_obj_t * ui_ThicknessLabel16;
extern lv_obj_t * ui_Thickness16;
extern lv_obj_t * ui_ThicknessPanel17;
extern lv_obj_t * ui_ThicknessLabel17;
extern lv_obj_t * ui_Thickness17;
extern lv_obj_t * ui_ThicknessPanel18;
extern lv_obj_t * ui_ThicknessLabel18;
extern lv_obj_t * ui_Thickness18;
extern lv_obj_t * ui_SummaryTkCon3;
extern lv_obj_t * ui_ThicknessPanel21;
extern lv_obj_t * ui_ThicknessLabel21;
extern lv_obj_t * ui_Thickness21;
extern lv_obj_t * ui_ThicknessPanel22;
extern lv_obj_t * ui_ThicknessLabel22;
extern lv_obj_t * ui_Thickness22;
extern lv_obj_t * ui_SummaryEndPanel;
extern lv_obj_t * ui_SummaryTimeoutPanel;
extern lv_obj_t * ui_SummaryTimeout;
extern lv_obj_t * ui_SummaryEndBtn;
// SCREEN: ui_SettingPage
void ui_SettingPage_screen_init(void);
extern lv_obj_t * ui_SettingPage;
extern lv_obj_t * ui_Brightness;
extern lv_obj_t * ui_BrightnessLabel;
extern lv_obj_t * ui_Sound;
extern lv_obj_t * ui_SoundLabel;
void ui_event_WifiPanel(lv_event_t * e);
extern lv_obj_t * ui_WifiPanel;
extern lv_obj_t * ui_WifiScanBtn;
extern lv_obj_t * ui_WifiScanLabel;
extern lv_obj_t * ui_WifiList;
extern lv_obj_t * ui_WifiSignal;
extern lv_obj_t * ui_WifiConnectBtn;
extern lv_obj_t * ui_WifiConnectLabel;
void ui_event_CloseSettingBtn(lv_event_t * e);
extern lv_obj_t * ui_CloseSettingBtn;
extern lv_obj_t * ui_CloseSettingLabel;
extern lv_obj_t * ui_WaitingToWifi;
extern lv_obj_t * ui_WifiSpinner;
extern lv_obj_t * ui_WifiKeyboardPanel;
extern lv_obj_t * ui_WifiKeyboard;
extern lv_obj_t * ui_WifiKeboardInput;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_402937210);    // assets\ดาวน์โหลด.png
LV_IMG_DECLARE(ui_img_206557904);    // assets\icons8-setting-48.png
LV_IMG_DECLARE(ui_img_1636676910);    // assets\icons8-exit-64.png

LV_FONT_DECLARE(ui_font_ProtestGuerrilla48);
LV_FONT_DECLARE(ui_font_Sarabun28);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
