// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_LoadingPage_screen_init(void)
{
    ui_LoadingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner = lv_spinner_create(ui_LoadingPage, 1000, 90);
    lv_obj_set_width(ui_Spinner, 245);
    lv_obj_set_height(ui_Spinner, 245);
    lv_obj_set_x(ui_Spinner, -218);
    lv_obj_set_y(ui_Spinner, 0);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Loading = lv_label_create(ui_Spinner);
    lv_obj_set_width(ui_Loading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Loading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Loading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loading, "Loading...");
    lv_obj_set_style_text_color(ui_Loading, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Loading, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_LoadingPage);
    lv_img_set_src(ui_Image2, &ui_img_402937210);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 147);
    lv_obj_set_y(ui_Image2, -18);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 150);

    ui_Title1 = lv_label_create(ui_LoadingPage);
    lv_obj_set_width(ui_Title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title1, 147);
    lv_obj_set_y(ui_Title1, 143);
    lv_obj_set_align(ui_Title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title1, "ONLINE WEIGHING SYSTEM");
    lv_obj_set_style_text_color(ui_Title1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title2 = lv_label_create(ui_LoadingPage);
    lv_obj_set_width(ui_Title2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title2, 144);
    lv_obj_set_y(ui_Title2, 176);
    lv_obj_set_align(ui_Title2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title2, "Created by Nattapon pondonko");
    lv_obj_set_style_text_color(ui_Title2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title3 = lv_label_create(ui_LoadingPage);
    lv_obj_set_width(ui_Title3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title3, 147);
    lv_obj_set_y(ui_Title3, 207);
    lv_obj_set_align(ui_Title3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title3, "Engineering Department");
    lv_obj_set_style_text_color(ui_Title3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Version = lv_label_create(ui_LoadingPage);
    lv_obj_set_width(ui_Version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Version, 91);
    lv_obj_set_y(ui_Version, 61);
    lv_obj_set_align(ui_Version, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Version, "V 5.0");
    lv_obj_set_style_text_color(ui_Version, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Version, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Version, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Process = lv_label_create(ui_LoadingPage);
    lv_obj_set_width(ui_Process, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Process, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Process, 3);
    lv_obj_set_y(ui_Process, 35);
    lv_label_set_text(ui_Process, "Process........");
    lv_obj_add_flag(ui_Process, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Process, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Process, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Process, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Process, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Process, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Process, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Process, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LoadingPage, ui_event_LoadingPage, LV_EVENT_ALL, NULL);

}
