// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_LoginPage_screen_init(void)
{
    ui_LoginPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoContainer = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_LogoContainer, 365);
    lv_obj_set_height(ui_LogoContainer, 74);
    lv_obj_set_x(ui_LogoContainer, -200);
    lv_obj_set_y(ui_LogoContainer, -163);
    lv_obj_set_align(ui_LogoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogoContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoContainer, lv_color_hex(0x7DDCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LogoContainer, lv_color_hex(0x009AFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LogoContainer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LogoContainer, lv_color_hex(0x89D0FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LogoContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LogoContainer, lv_color_hex(0x10A1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LogoContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LogoContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LogoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Polipharm = lv_label_create(ui_LogoContainer);
    lv_obj_set_width(ui_Polipharm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Polipharm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Polipharm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Polipharm, "POLIPHARM");
    lv_obj_set_style_text_color(ui_Polipharm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Polipharm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Polipharm, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTimePanel = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_DateTimePanel, 365);
    lv_obj_set_height(ui_DateTimePanel, 310);
    lv_obj_set_x(ui_DateTimePanel, -200);
    lv_obj_set_y(ui_DateTimePanel, 47);
    lv_obj_set_align(ui_DateTimePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DateTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DateTimePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DateTimePanel, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DateTimePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DateTimePanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DateTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_DateTimePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_DateTimePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HoursPanel = lv_obj_create(ui_DateTimePanel);
    lv_obj_set_width(ui_HoursPanel, 80);
    lv_obj_set_height(ui_HoursPanel, 66);
    lv_obj_set_x(ui_HoursPanel, -115);
    lv_obj_set_y(ui_HoursPanel, -100);
    lv_obj_set_align(ui_HoursPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HoursPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_HoursPanel, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HoursPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HoursPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HoursPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hours = lv_label_create(ui_HoursPanel);
    lv_obj_set_width(ui_Hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hours, "--");
    lv_obj_set_style_text_color(ui_Hours, lv_color_hex(0xF5566D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Hours, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hours, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HM = lv_label_create(ui_DateTimePanel);
    lv_obj_set_width(ui_HM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HM, -58);
    lv_obj_set_y(ui_HM, -105);
    lv_obj_set_align(ui_HM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HM, ":");
    lv_obj_set_style_text_color(ui_HM, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinutesPanel = lv_obj_create(ui_DateTimePanel);
    lv_obj_set_width(ui_MinutesPanel, 80);
    lv_obj_set_height(ui_MinutesPanel, 66);
    lv_obj_set_x(ui_MinutesPanel, 0);
    lv_obj_set_y(ui_MinutesPanel, -100);
    lv_obj_set_align(ui_MinutesPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MinutesPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_MinutesPanel, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MinutesPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MinutesPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MinutesPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutes = lv_label_create(ui_MinutesPanel);
    lv_obj_set_width(ui_Minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Minutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minutes, "--");
    lv_obj_set_style_text_color(ui_Minutes, lv_color_hex(0xF5566D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Minutes, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Minutes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minutes, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MS = lv_label_create(ui_DateTimePanel);
    lv_obj_set_width(ui_MS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MS, 58);
    lv_obj_set_y(ui_MS, -105);
    lv_obj_set_align(ui_MS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MS, ":");
    lv_obj_set_style_text_color(ui_MS, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MS, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondsPanel = lv_obj_create(ui_DateTimePanel);
    lv_obj_set_width(ui_SecondsPanel, 80);
    lv_obj_set_height(ui_SecondsPanel, 66);
    lv_obj_set_x(ui_SecondsPanel, 115);
    lv_obj_set_y(ui_SecondsPanel, -100);
    lv_obj_set_align(ui_SecondsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SecondsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SecondsPanel, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SecondsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SecondsPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SecondsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Seconds = lv_label_create(ui_SecondsPanel);
    lv_obj_set_width(ui_Seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Seconds, "--");
    lv_obj_set_style_text_color(ui_Seconds, lv_color_hex(0xF5566D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Seconds, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Seconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Seconds, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatePanel = lv_obj_create(ui_DateTimePanel);
    lv_obj_set_width(ui_DatePanel, 305);
    lv_obj_set_height(ui_DatePanel, 75);
    lv_obj_set_align(ui_DatePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_DatePanel, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DatePanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_DatePanel);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "MM/DD/YYYY");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xF5566D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Date, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Date, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MsgRfidScan = lv_label_create(ui_DateTimePanel);
    lv_obj_set_width(ui_MsgRfidScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MsgRfidScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MsgRfidScan, 0);
    lv_obj_set_y(ui_MsgRfidScan, 105);
    lv_obj_set_align(ui_MsgRfidScan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgRfidScan, "แสกนบัตรพนักงาน");
    lv_obj_set_style_text_font(ui_MsgRfidScan, &ui_font_Sarabun28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrMsgRfidScan = lv_label_create(ui_DateTimePanel);
    lv_obj_set_width(ui_ErrMsgRfidScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ErrMsgRfidScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrMsgRfidScan, 0);
    lv_obj_set_y(ui_ErrMsgRfidScan, 105);
    lv_obj_set_align(ui_ErrMsgRfidScan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrMsgRfidScan, "ไม่พบข้อมูลบัตรพนักงาน");
    lv_obj_add_flag(ui_ErrMsgRfidScan, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_ErrMsgRfidScan, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrMsgRfidScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrMsgRfidScan, &ui_font_Sarabun28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginPanel = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_LoginPanel, 366);
    lv_obj_set_height(ui_LoginPanel, 401);
    lv_obj_set_x(ui_LoginPanel, 195);
    lv_obj_set_y(ui_LoginPanel, 0);
    lv_obj_set_align(ui_LoginPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LoginPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LoginPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LoginPanel, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LoginPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LoginPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LoginPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LoginPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LoginPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitlePanel = lv_obj_create(ui_LoginPanel);
    lv_obj_set_width(ui_TitlePanel, 368);
    lv_obj_set_height(ui_TitlePanel, 62);
    lv_obj_set_x(ui_TitlePanel, 0);
    lv_obj_set_y(ui_TitlePanel, -169);
    lv_obj_set_align(ui_TitlePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TitlePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitlePanel, lv_color_hex(0xA8ABFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TitlePanel, lv_color_hex(0x0008CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TitlePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginTitle = lv_label_create(ui_TitlePanel);
    lv_obj_set_width(ui_LoginTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoginTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoginTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginTitle, "ONLINE WEIGHING SYSTEM");
    lv_obj_set_style_text_color(ui_LoginTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoginTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleIMG = lv_img_create(ui_LoginPanel);
    lv_img_set_src(ui_ScaleIMG, &ui_img_402937210);
    lv_obj_set_width(ui_ScaleIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScaleIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScaleIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ScaleIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ScaleIMG, 100);

    ui_RfidPanel = lv_obj_create(ui_LoginPanel);
    lv_obj_set_width(ui_RfidPanel, 315);
    lv_obj_set_height(ui_RfidPanel, 65);
    lv_obj_set_x(ui_RfidPanel, 0);
    lv_obj_set_y(ui_RfidPanel, 150);
    lv_obj_set_align(ui_RfidPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RfidPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RfidPanel, lv_color_hex(0xA4A1A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RfidPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RfidPanel, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RfidPanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFID = lv_label_create(ui_RfidPanel);
    lv_obj_set_width(ui_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFID, "XXXXXXXXXX");
    lv_obj_set_style_text_color(ui_RFID, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RFID, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBtn = lv_btn_create(ui_LoginPanel);
    lv_obj_set_width(ui_SettingBtn, 46);
    lv_obj_set_height(ui_SettingBtn, 46);
    lv_obj_set_x(ui_SettingBtn, 145);
    lv_obj_set_y(ui_SettingBtn, -93);
    lv_obj_set_align(ui_SettingBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingBtn, &ui_img_206557904, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LoginPage, ui_event_LoginPage, LV_EVENT_ALL, NULL);

}
