// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_SummaryPage_screen_init(void)
{
    ui_SummaryPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SummaryPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SummaryTitlePanel = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryTitlePanel, 500);
    lv_obj_set_height(ui_SummaryTitlePanel, 61);
    lv_obj_set_x(ui_SummaryTitlePanel, 0);
    lv_obj_set_y(ui_SummaryTitlePanel, -195);
    lv_obj_set_align(ui_SummaryTitlePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SummaryTitlePanel, lv_color_hex(0x006DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryTitlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SummaryTitlePanel, lv_color_hex(0x5499FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SummaryTitlePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SummaryTitlePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SummaryTitlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTitle = lv_label_create(ui_SummaryTitlePanel);
    lv_obj_set_width(ui_SummaryTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SummaryTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SummaryTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SummaryTitle, "Summary of weighing data");
    lv_obj_set_style_text_font(ui_SummaryTitle, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryW1Panel = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryW1Panel, 185);
    lv_obj_set_height(ui_SummaryW1Panel, 98);
    lv_obj_set_x(ui_SummaryW1Panel, -295);
    lv_obj_set_y(ui_SummaryW1Panel, -285);
    lv_obj_set_align(ui_SummaryW1Panel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SummaryW1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SummaryW1Panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SummaryW1Panel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryW1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SummaryW1Panel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SummaryW1Panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SummaryW1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SummaryW1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SummaryW1Panel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SummaryW1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSumW1 = lv_label_create(ui_SummaryW1Panel);
    lv_obj_set_width(ui_TitleSumW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSumW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSumW1, 0);
    lv_obj_set_y(ui_TitleSumW1, -50);
    lv_obj_set_align(ui_TitleSumW1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleSumW1, "Weight1");
    lv_obj_set_style_text_color(ui_TitleSumW1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSumW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSumW1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleSumW1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleSumW1, lv_color_hex(0x18955A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleSumW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleSumW1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleSumW1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleSumW1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleSumW1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumW1 = lv_label_create(ui_SummaryW1Panel);
    lv_obj_set_width(ui_SumW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SumW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SumW1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SumW1, "XX.XXX");
    lv_obj_set_style_text_color(ui_SumW1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SumW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SumW1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryW2Panel = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryW2Panel, 187);
    lv_obj_set_height(ui_SummaryW2Panel, 98);
    lv_obj_set_x(ui_SummaryW2Panel, -100);
    lv_obj_set_y(ui_SummaryW2Panel, -285);
    lv_obj_set_align(ui_SummaryW2Panel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SummaryW2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SummaryW2Panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SummaryW2Panel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryW2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SummaryW2Panel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SummaryW2Panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SummaryW2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SummaryW2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SummaryW2Panel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SummaryW2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSumW2 = lv_label_create(ui_SummaryW2Panel);
    lv_obj_set_width(ui_TitleSumW2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSumW2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSumW2, 0);
    lv_obj_set_y(ui_TitleSumW2, -50);
    lv_obj_set_align(ui_TitleSumW2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleSumW2, "Weight2");
    lv_obj_set_style_text_color(ui_TitleSumW2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSumW2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSumW2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleSumW2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleSumW2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleSumW2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleSumW2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleSumW2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleSumW2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleSumW2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumW2 = lv_label_create(ui_SummaryW2Panel);
    lv_obj_set_width(ui_SumW2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SumW2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SumW2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SumW2, "XX.XXX");
    lv_obj_set_style_text_color(ui_SumW2, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SumW2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SumW2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryAveragePanel = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryAveragePanel, 189);
    lv_obj_set_height(ui_SummaryAveragePanel, 98);
    lv_obj_set_x(ui_SummaryAveragePanel, 100);
    lv_obj_set_y(ui_SummaryAveragePanel, -285);
    lv_obj_set_align(ui_SummaryAveragePanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SummaryAveragePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SummaryAveragePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SummaryAveragePanel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryAveragePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SummaryAveragePanel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SummaryAveragePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SummaryAveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SummaryAveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SummaryAveragePanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SummaryAveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSumAverage = lv_label_create(ui_SummaryAveragePanel);
    lv_obj_set_width(ui_TitleSumAverage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSumAverage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSumAverage, 0);
    lv_obj_set_y(ui_TitleSumAverage, -50);
    lv_obj_set_align(ui_TitleSumAverage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleSumAverage, "Average");
    lv_obj_set_style_text_color(ui_TitleSumAverage, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSumAverage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSumAverage, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleSumAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleSumAverage, lv_color_hex(0xFF0091), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleSumAverage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleSumAverage, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleSumAverage, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleSumAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleSumAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumAverage = lv_label_create(ui_SummaryAveragePanel);
    lv_obj_set_width(ui_SumAverage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SumAverage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SumAverage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SumAverage, "XX.XXX");
    lv_obj_set_style_text_color(ui_SumAverage, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SumAverage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SumAverage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryPercent = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryPercent, 184);
    lv_obj_set_height(ui_SummaryPercent, 98);
    lv_obj_set_x(ui_SummaryPercent, 295);
    lv_obj_set_y(ui_SummaryPercent, -285);
    lv_obj_set_align(ui_SummaryPercent, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SummaryPercent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SummaryPercent, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SummaryPercent, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SummaryPercent, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SummaryPercent, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SummaryPercent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SummaryPercent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SummaryPercent, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SummaryPercent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSumPercent = lv_label_create(ui_SummaryPercent);
    lv_obj_set_width(ui_TitleSumPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSumPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSumPercent, 0);
    lv_obj_set_y(ui_TitleSumPercent, -50);
    lv_obj_set_align(ui_TitleSumPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleSumPercent, "Percentage");
    lv_obj_set_style_text_color(ui_TitleSumPercent, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSumPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSumPercent, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleSumPercent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleSumPercent, lv_color_hex(0x18955A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleSumPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleSumPercent, 33, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleSumPercent, 33, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleSumPercent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleSumPercent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumPercent = lv_label_create(ui_SummaryPercent);
    lv_obj_set_width(ui_SumPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SumPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SumPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SumPercent, "XX.XX%");
    lv_obj_set_style_text_color(ui_SumPercent, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SumPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SumPercent, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTkPanel = lv_obj_create(ui_SummaryPage);
    lv_obj_set_width(ui_SummaryTkPanel, 765);
    lv_obj_set_height(ui_SummaryTkPanel, 231);
    lv_obj_set_x(ui_SummaryTkPanel, -5);
    lv_obj_set_y(ui_SummaryTkPanel, 99);
    lv_obj_set_align(ui_SummaryTkPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTkPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SummaryTkPanel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SummaryTkPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SummaryTkPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SummaryTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SummaryTkPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SummaryTkPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinTkPanel = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_set_width(ui_MinTkPanel, 151);
    lv_obj_set_height(ui_MinTkPanel, 90);
    lv_obj_set_x(ui_MinTkPanel, 78);
    lv_obj_set_y(ui_MinTkPanel, 10);
    lv_obj_set_align(ui_MinTkPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_MinTkPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MinTkPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinTkPanel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinTkPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MinTkPanel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MinTkPanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MinTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MinTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MinTkPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MinTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleMinTk = lv_label_create(ui_MinTkPanel);
    lv_obj_set_width(ui_TitleMinTk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleMinTk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleMinTk, 0);
    lv_obj_set_y(ui_TitleMinTk, -46);
    lv_obj_set_align(ui_TitleMinTk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleMinTk, "Min");
    lv_obj_set_style_text_color(ui_TitleMinTk, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleMinTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleMinTk, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleMinTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleMinTk, lv_color_hex(0x5F6060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleMinTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleMinTk, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleMinTk, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleMinTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleMinTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinTk = lv_label_create(ui_MinTkPanel);
    lv_obj_set_width(ui_MinTk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinTk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinTk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinTk, "XX.XX");
    lv_obj_set_style_text_color(ui_MinTk, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinTk, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxTkPanel = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_set_width(ui_MaxTkPanel, 157);
    lv_obj_set_height(ui_MaxTkPanel, 90);
    lv_obj_set_x(ui_MaxTkPanel, 268);
    lv_obj_set_y(ui_MaxTkPanel, 10);
    lv_obj_set_align(ui_MaxTkPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_MaxTkPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MaxTkPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MaxTkPanel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxTkPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MaxTkPanel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MaxTkPanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MaxTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MaxTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MaxTkPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MaxTkPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleMaxTk = lv_label_create(ui_MaxTkPanel);
    lv_obj_set_width(ui_TitleMaxTk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleMaxTk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleMaxTk, 0);
    lv_obj_set_y(ui_TitleMaxTk, -46);
    lv_obj_set_align(ui_TitleMaxTk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleMaxTk, "Max");
    lv_obj_set_style_text_color(ui_TitleMaxTk, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleMaxTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleMaxTk, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleMaxTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleMaxTk, lv_color_hex(0x5A6162), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleMaxTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleMaxTk, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleMaxTk, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleMaxTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleMaxTk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxTk = lv_label_create(ui_MaxTkPanel);
    lv_obj_set_width(ui_MaxTk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxTk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MaxTk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxTk, "XX.XX");
    lv_obj_set_style_text_color(ui_MaxTk, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxTk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxTk, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTkCon1 = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_remove_style_all(ui_SummaryTkCon1);
    lv_obj_set_width(ui_SummaryTkCon1, 177);
    lv_obj_set_height(ui_SummaryTkCon1, 215);
    lv_obj_set_x(ui_SummaryTkCon1, -275);
    lv_obj_set_y(ui_SummaryTkCon1, 0);
    lv_obj_set_align(ui_SummaryTkCon1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTkCon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessPanel11 = lv_obj_create(ui_SummaryTkCon1);
    lv_obj_set_width(ui_ThicknessPanel11, 138);
    lv_obj_set_height(ui_ThicknessPanel11, 44);
    lv_obj_set_x(ui_ThicknessPanel11, 0);
    lv_obj_set_y(ui_ThicknessPanel11, -76);
    lv_obj_set_align(ui_ThicknessPanel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel11 = lv_label_create(ui_ThicknessPanel11);
    lv_obj_set_width(ui_ThicknessLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel11, -20);
    lv_obj_set_y(ui_ThicknessLabel11, 0);
    lv_obj_set_align(ui_ThicknessLabel11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel11, "No.1");
    lv_obj_set_style_text_color(ui_ThicknessLabel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel11, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel11, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel11, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness11 = lv_label_create(ui_ThicknessPanel11);
    lv_obj_set_width(ui_Thickness11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness11, 35);
    lv_obj_set_y(ui_Thickness11, 0);
    lv_obj_set_align(ui_Thickness11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness11, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness11, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel12 = lv_obj_create(ui_SummaryTkCon1);
    lv_obj_set_width(ui_ThicknessPanel12, 138);
    lv_obj_set_height(ui_ThicknessPanel12, 44);
    lv_obj_set_x(ui_ThicknessPanel12, 0);
    lv_obj_set_y(ui_ThicknessPanel12, -25);
    lv_obj_set_align(ui_ThicknessPanel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel12 = lv_label_create(ui_ThicknessPanel12);
    lv_obj_set_width(ui_ThicknessLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel12, -20);
    lv_obj_set_y(ui_ThicknessLabel12, 0);
    lv_obj_set_align(ui_ThicknessLabel12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel12, "No.2");
    lv_obj_set_style_text_color(ui_ThicknessLabel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel12, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel12, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel12, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness12 = lv_label_create(ui_ThicknessPanel12);
    lv_obj_set_width(ui_Thickness12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness12, 35);
    lv_obj_set_y(ui_Thickness12, 0);
    lv_obj_set_align(ui_Thickness12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness12, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness12, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel13 = lv_obj_create(ui_SummaryTkCon1);
    lv_obj_set_width(ui_ThicknessPanel13, 138);
    lv_obj_set_height(ui_ThicknessPanel13, 44);
    lv_obj_set_x(ui_ThicknessPanel13, 0);
    lv_obj_set_y(ui_ThicknessPanel13, 27);
    lv_obj_set_align(ui_ThicknessPanel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel13 = lv_label_create(ui_ThicknessPanel13);
    lv_obj_set_width(ui_ThicknessLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel13, -20);
    lv_obj_set_y(ui_ThicknessLabel13, 0);
    lv_obj_set_align(ui_ThicknessLabel13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel13, "No.3");
    lv_obj_set_style_text_color(ui_ThicknessLabel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel13, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel13, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel13, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness13 = lv_label_create(ui_ThicknessPanel13);
    lv_obj_set_width(ui_Thickness13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness13, 35);
    lv_obj_set_y(ui_Thickness13, 0);
    lv_obj_set_align(ui_Thickness13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness13, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel14 = lv_obj_create(ui_SummaryTkCon1);
    lv_obj_set_width(ui_ThicknessPanel14, 138);
    lv_obj_set_height(ui_ThicknessPanel14, 44);
    lv_obj_set_x(ui_ThicknessPanel14, 0);
    lv_obj_set_y(ui_ThicknessPanel14, 79);
    lv_obj_set_align(ui_ThicknessPanel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel14 = lv_label_create(ui_ThicknessPanel14);
    lv_obj_set_width(ui_ThicknessLabel14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel14, -20);
    lv_obj_set_y(ui_ThicknessLabel14, 0);
    lv_obj_set_align(ui_ThicknessLabel14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel14, "No.4");
    lv_obj_set_style_text_color(ui_ThicknessLabel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel14, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel14, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel14, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness14 = lv_label_create(ui_ThicknessPanel14);
    lv_obj_set_width(ui_Thickness14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness14, 35);
    lv_obj_set_y(ui_Thickness14, 0);
    lv_obj_set_align(ui_Thickness14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness14, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness14, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTkCon2 = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_remove_style_all(ui_SummaryTkCon2);
    lv_obj_set_width(ui_SummaryTkCon2, 177);
    lv_obj_set_height(ui_SummaryTkCon2, 215);
    lv_obj_set_x(ui_SummaryTkCon2, -97);
    lv_obj_set_y(ui_SummaryTkCon2, 0);
    lv_obj_set_align(ui_SummaryTkCon2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTkCon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessPanel15 = lv_obj_create(ui_SummaryTkCon2);
    lv_obj_set_width(ui_ThicknessPanel15, 138);
    lv_obj_set_height(ui_ThicknessPanel15, 44);
    lv_obj_set_x(ui_ThicknessPanel15, 0);
    lv_obj_set_y(ui_ThicknessPanel15, -76);
    lv_obj_set_align(ui_ThicknessPanel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel15 = lv_label_create(ui_ThicknessPanel15);
    lv_obj_set_width(ui_ThicknessLabel15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel15, -20);
    lv_obj_set_y(ui_ThicknessLabel15, 0);
    lv_obj_set_align(ui_ThicknessLabel15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel15, "No.5");
    lv_obj_set_style_text_color(ui_ThicknessLabel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel15, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel15, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel15, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness15 = lv_label_create(ui_ThicknessPanel15);
    lv_obj_set_width(ui_Thickness15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness15, 35);
    lv_obj_set_y(ui_Thickness15, 0);
    lv_obj_set_align(ui_Thickness15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness15, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness15, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel16 = lv_obj_create(ui_SummaryTkCon2);
    lv_obj_set_width(ui_ThicknessPanel16, 138);
    lv_obj_set_height(ui_ThicknessPanel16, 44);
    lv_obj_set_x(ui_ThicknessPanel16, 0);
    lv_obj_set_y(ui_ThicknessPanel16, -25);
    lv_obj_set_align(ui_ThicknessPanel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel16 = lv_label_create(ui_ThicknessPanel16);
    lv_obj_set_width(ui_ThicknessLabel16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel16, -20);
    lv_obj_set_y(ui_ThicknessLabel16, 0);
    lv_obj_set_align(ui_ThicknessLabel16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel16, "No.6");
    lv_obj_set_style_text_color(ui_ThicknessLabel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel16, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel16, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel16, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness16 = lv_label_create(ui_ThicknessPanel16);
    lv_obj_set_width(ui_Thickness16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness16, 35);
    lv_obj_set_y(ui_Thickness16, 0);
    lv_obj_set_align(ui_Thickness16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness16, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness16, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel17 = lv_obj_create(ui_SummaryTkCon2);
    lv_obj_set_width(ui_ThicknessPanel17, 138);
    lv_obj_set_height(ui_ThicknessPanel17, 44);
    lv_obj_set_x(ui_ThicknessPanel17, 0);
    lv_obj_set_y(ui_ThicknessPanel17, 27);
    lv_obj_set_align(ui_ThicknessPanel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel17 = lv_label_create(ui_ThicknessPanel17);
    lv_obj_set_width(ui_ThicknessLabel17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel17, -20);
    lv_obj_set_y(ui_ThicknessLabel17, 0);
    lv_obj_set_align(ui_ThicknessLabel17, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel17, "No.7");
    lv_obj_set_style_text_color(ui_ThicknessLabel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel17, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel17, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel17, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel17, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness17 = lv_label_create(ui_ThicknessPanel17);
    lv_obj_set_width(ui_Thickness17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness17, 35);
    lv_obj_set_y(ui_Thickness17, 0);
    lv_obj_set_align(ui_Thickness17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness17, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness17, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness17, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel18 = lv_obj_create(ui_SummaryTkCon2);
    lv_obj_set_width(ui_ThicknessPanel18, 138);
    lv_obj_set_height(ui_ThicknessPanel18, 44);
    lv_obj_set_x(ui_ThicknessPanel18, 0);
    lv_obj_set_y(ui_ThicknessPanel18, 79);
    lv_obj_set_align(ui_ThicknessPanel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel18 = lv_label_create(ui_ThicknessPanel18);
    lv_obj_set_width(ui_ThicknessLabel18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel18, -20);
    lv_obj_set_y(ui_ThicknessLabel18, 0);
    lv_obj_set_align(ui_ThicknessLabel18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel18, "No.8");
    lv_obj_set_style_text_color(ui_ThicknessLabel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel18, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel18, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel18, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel18, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness18 = lv_label_create(ui_ThicknessPanel18);
    lv_obj_set_width(ui_Thickness18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness18, 35);
    lv_obj_set_y(ui_Thickness18, 0);
    lv_obj_set_align(ui_Thickness18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness18, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness18, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness18, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTkCon3 = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_remove_style_all(ui_SummaryTkCon3);
    lv_obj_set_width(ui_SummaryTkCon3, 177);
    lv_obj_set_height(ui_SummaryTkCon3, 106);
    lv_obj_set_x(ui_SummaryTkCon3, 73);
    lv_obj_set_y(ui_SummaryTkCon3, -50);
    lv_obj_set_align(ui_SummaryTkCon3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTkCon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessPanel21 = lv_obj_create(ui_SummaryTkCon3);
    lv_obj_set_width(ui_ThicknessPanel21, 138);
    lv_obj_set_height(ui_ThicknessPanel21, 44);
    lv_obj_set_x(ui_ThicknessPanel21, 0);
    lv_obj_set_y(ui_ThicknessPanel21, -26);
    lv_obj_set_align(ui_ThicknessPanel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel21 = lv_label_create(ui_ThicknessPanel21);
    lv_obj_set_width(ui_ThicknessLabel21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel21, -20);
    lv_obj_set_y(ui_ThicknessLabel21, 0);
    lv_obj_set_align(ui_ThicknessLabel21, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel21, "No.9");
    lv_obj_set_style_text_color(ui_ThicknessLabel21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel21, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel21, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel21, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness21 = lv_label_create(ui_ThicknessPanel21);
    lv_obj_set_width(ui_Thickness21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness21, 35);
    lv_obj_set_y(ui_Thickness21, 0);
    lv_obj_set_align(ui_Thickness21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness21, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness21, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel22 = lv_obj_create(ui_SummaryTkCon3);
    lv_obj_set_width(ui_ThicknessPanel22, 138);
    lv_obj_set_height(ui_ThicknessPanel22, 44);
    lv_obj_set_x(ui_ThicknessPanel22, 0);
    lv_obj_set_y(ui_ThicknessPanel22, 25);
    lv_obj_set_align(ui_ThicknessPanel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel22 = lv_label_create(ui_ThicknessPanel22);
    lv_obj_set_width(ui_ThicknessLabel22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel22, -20);
    lv_obj_set_y(ui_ThicknessLabel22, 0);
    lv_obj_set_align(ui_ThicknessLabel22, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel22, "No.10");
    lv_obj_set_style_text_color(ui_ThicknessLabel22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel22, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel22, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel22, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel22, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel22, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel22, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness22 = lv_label_create(ui_ThicknessPanel22);
    lv_obj_set_width(ui_Thickness22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness22, 35);
    lv_obj_set_y(ui_Thickness22, 0);
    lv_obj_set_align(ui_Thickness22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness22, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryEndPanel = lv_obj_create(ui_SummaryTkPanel);
    lv_obj_set_width(ui_SummaryEndPanel, 198);
    lv_obj_set_height(ui_SummaryEndPanel, 93);
    lv_obj_set_x(ui_SummaryEndPanel, 264);
    lv_obj_set_y(ui_SummaryEndPanel, -49);
    lv_obj_set_align(ui_SummaryEndPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryEndPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SummaryEndPanel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SummaryEndPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SummaryEndPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SummaryEndPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTimeoutPanel = lv_obj_create(ui_SummaryEndPanel);
    lv_obj_set_width(ui_SummaryTimeoutPanel, 81);
    lv_obj_set_height(ui_SummaryTimeoutPanel, 64);
    lv_obj_set_x(ui_SummaryTimeoutPanel, -36);
    lv_obj_set_y(ui_SummaryTimeoutPanel, 0);
    lv_obj_set_align(ui_SummaryTimeoutPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SummaryTimeoutPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SummaryTimeoutPanel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SummaryTimeoutPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SummaryTimeoutPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SummaryTimeoutPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryTimeout = lv_label_create(ui_SummaryTimeoutPanel);
    lv_obj_set_width(ui_SummaryTimeout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SummaryTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SummaryTimeout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SummaryTimeout, "60");
    lv_obj_set_style_text_color(ui_SummaryTimeout, lv_color_hex(0xFE0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SummaryTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SummaryTimeout, &ui_font_ProtestGuerrilla48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SummaryEndBtn = lv_btn_create(ui_SummaryEndPanel);
    lv_obj_set_width(ui_SummaryEndBtn, 74);
    lv_obj_set_height(ui_SummaryEndBtn, 75);
    lv_obj_set_x(ui_SummaryEndBtn, 52);
    lv_obj_set_y(ui_SummaryEndBtn, -1);
    lv_obj_set_align(ui_SummaryEndBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SummaryEndBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SummaryEndBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SummaryEndBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SummaryEndBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SummaryEndBtn, &ui_img_1636676910, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SummaryPage, ui_event_SummaryPage, LV_EVENT_ALL, NULL);

}
