// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_TabletCharacteristicsPage_screen_init(void)
{
    ui_TabletCharacteristicsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TabletCharacteristicsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabletCharacteristicsPanel = lv_obj_create(ui_TabletCharacteristicsPage);
    lv_obj_set_width(ui_TabletCharacteristicsPanel, 547);
    lv_obj_set_height(ui_TabletCharacteristicsPanel, 70);
    lv_obj_set_x(ui_TabletCharacteristicsPanel, 0);
    lv_obj_set_y(ui_TabletCharacteristicsPanel, -179);
    lv_obj_set_align(ui_TabletCharacteristicsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabletCharacteristicsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabletCharacteristicsPanel, lv_color_hex(0x006DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabletCharacteristicsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TabletCharacteristicsPanel, lv_color_hex(0x5499FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TabletCharacteristicsPanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabletCharacteristics = lv_label_create(ui_TabletCharacteristicsPanel);
    lv_obj_set_width(ui_TabletCharacteristics, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TabletCharacteristics, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TabletCharacteristics, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TabletCharacteristics, "Tablet characteristics");
    lv_obj_set_style_text_color(ui_TabletCharacteristics, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabletCharacteristics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabletCharacteristics, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NomalPillsBtn = lv_btn_create(ui_TabletCharacteristicsPage);
    lv_obj_set_width(ui_NomalPillsBtn, 175);
    lv_obj_set_height(ui_NomalPillsBtn, 75);
    lv_obj_set_x(ui_NomalPillsBtn, -130);
    lv_obj_set_y(ui_NomalPillsBtn, 185);
    lv_obj_set_align(ui_NomalPillsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NomalPillsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NomalPillsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NomalPillsBtn, lv_color_hex(0x067729), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NomalPillsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_NomalPillsBtn, lv_color_hex(0x1AE283), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_NomalPillsBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NomalLabel = lv_label_create(ui_NomalPillsBtn);
    lv_obj_set_width(ui_NomalLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NomalLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NomalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NomalLabel, "ปกติ");
    lv_obj_set_style_text_font(ui_NomalLabel, &ui_font_Sarabun28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotgoodPillsBtn = lv_btn_create(ui_TabletCharacteristicsPage);
    lv_obj_set_width(ui_NotgoodPillsBtn, 175);
    lv_obj_set_height(ui_NotgoodPillsBtn, 75);
    lv_obj_set_x(ui_NotgoodPillsBtn, 130);
    lv_obj_set_y(ui_NotgoodPillsBtn, 186);
    lv_obj_set_align(ui_NotgoodPillsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NotgoodPillsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NotgoodPillsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NotgoodPillsBtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotgoodPillsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_NotgoodPillsBtn, lv_color_hex(0xF66060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_NotgoodPillsBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotgoodLabel = lv_label_create(ui_NotgoodPillsBtn);
    lv_obj_set_width(ui_NotgoodLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotgoodLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NotgoodLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NotgoodLabel, "ผิดปกติ");
    lv_obj_set_style_text_font(ui_NotgoodLabel, &ui_font_Sarabun28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PillsTopIMG = lv_img_create(ui_TabletCharacteristicsPage);
    lv_img_set_src(ui_PillsTopIMG, &ui_img_206557904);
    lv_obj_set_width(ui_PillsTopIMG, 200);
    lv_obj_set_height(ui_PillsTopIMG, 200);
    lv_obj_set_x(ui_PillsTopIMG, -130);
    lv_obj_set_y(ui_PillsTopIMG, -10);
    lv_obj_set_align(ui_PillsTopIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PillsTopIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PillsTopIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PillsTopIMG, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PillsTopIMG, lv_color_hex(0xC7A31B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PillsTopIMG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PillsTopIMG, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PillsBelowIMG = lv_img_create(ui_TabletCharacteristicsPage);
    lv_img_set_src(ui_PillsBelowIMG, &ui_img_206557904);
    lv_obj_set_width(ui_PillsBelowIMG, 200);
    lv_obj_set_height(ui_PillsBelowIMG, 200);
    lv_obj_set_x(ui_PillsBelowIMG, 130);
    lv_obj_set_y(ui_PillsBelowIMG, -10);
    lv_obj_set_align(ui_PillsBelowIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PillsBelowIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PillsBelowIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PillsBelowIMG, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PillsBelowIMG, lv_color_hex(0xC5A118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PillsBelowIMG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PillsBelowIMG, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PillsTopLabel = lv_label_create(ui_TabletCharacteristicsPage);
    lv_obj_set_width(ui_PillsTopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PillsTopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PillsTopLabel, -135);
    lv_obj_set_y(ui_PillsTopLabel, 112);
    lv_obj_set_align(ui_PillsTopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PillsTopLabel, "Top");
    lv_obj_set_style_text_color(ui_PillsTopLabel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PillsTopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PillsTopLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PillsBelowLabel = lv_label_create(ui_TabletCharacteristicsPage);
    lv_obj_set_width(ui_PillsBelowLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PillsBelowLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PillsBelowLabel, 135);
    lv_obj_set_y(ui_PillsBelowLabel, 112);
    lv_obj_set_align(ui_PillsBelowLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PillsBelowLabel, "Below");
    lv_obj_set_style_text_color(ui_PillsBelowLabel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PillsBelowLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PillsBelowLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TabletCharacteristicsPage, ui_event_TabletCharacteristicsPage, LV_EVENT_ALL, NULL);

}
