// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_ThicknessPage_screen_init(void)
{
    ui_ThicknessPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ThicknessPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessMainPanel = lv_obj_create(ui_ThicknessPage);
    lv_obj_set_width(ui_ThicknessMainPanel, 737);
    lv_obj_set_height(ui_ThicknessMainPanel, 368);
    lv_obj_set_x(ui_ThicknessMainPanel, 0);
    lv_obj_set_y(ui_ThicknessMainPanel, -39);
    lv_obj_set_align(ui_ThicknessMainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_width(ui_ThicknessMainPanel, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ThicknessMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ThicknessMainPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ThicknessMainPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessA = lv_obj_create(ui_ThicknessMainPanel);
    lv_obj_remove_style_all(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessA, 215);
    lv_obj_set_height(ui_ThicknessA, 306);
    lv_obj_set_x(ui_ThicknessA, -200);
    lv_obj_set_y(ui_ThicknessA, 17);
    lv_obj_set_align(ui_ThicknessA, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessPanel1 = lv_obj_create(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessPanel1, 185);
    lv_obj_set_height(ui_ThicknessPanel1, 47);
    lv_obj_set_x(ui_ThicknessPanel1, 0);
    lv_obj_set_y(ui_ThicknessPanel1, -115);
    lv_obj_set_align(ui_ThicknessPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel1 = lv_label_create(ui_ThicknessPanel1);
    lv_obj_set_width(ui_ThicknessLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel1, -20);
    lv_obj_set_y(ui_ThicknessLabel1, 0);
    lv_obj_set_align(ui_ThicknessLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel1, "No.1");
    lv_obj_set_style_text_color(ui_ThicknessLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel1, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness1 = lv_label_create(ui_ThicknessPanel1);
    lv_obj_set_width(ui_Thickness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness1, 40);
    lv_obj_set_y(ui_Thickness1, 0);
    lv_obj_set_align(ui_Thickness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness1, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel2 = lv_obj_create(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessPanel2, 185);
    lv_obj_set_height(ui_ThicknessPanel2, 47);
    lv_obj_set_x(ui_ThicknessPanel2, 0);
    lv_obj_set_y(ui_ThicknessPanel2, -57);
    lv_obj_set_align(ui_ThicknessPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel2 = lv_label_create(ui_ThicknessPanel2);
    lv_obj_set_width(ui_ThicknessLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel2, -20);
    lv_obj_set_y(ui_ThicknessLabel2, 0);
    lv_obj_set_align(ui_ThicknessLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel2, "No.2");
    lv_obj_set_style_text_color(ui_ThicknessLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel2, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness2 = lv_label_create(ui_ThicknessPanel2);
    lv_obj_set_width(ui_Thickness2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness2, 40);
    lv_obj_set_y(ui_Thickness2, 0);
    lv_obj_set_align(ui_Thickness2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness2, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel3 = lv_obj_create(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessPanel3, 185);
    lv_obj_set_height(ui_ThicknessPanel3, 47);
    lv_obj_set_align(ui_ThicknessPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel3 = lv_label_create(ui_ThicknessPanel3);
    lv_obj_set_width(ui_ThicknessLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel3, -20);
    lv_obj_set_y(ui_ThicknessLabel3, 0);
    lv_obj_set_align(ui_ThicknessLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel3, "No.3");
    lv_obj_set_style_text_color(ui_ThicknessLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel3, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness3 = lv_label_create(ui_ThicknessPanel3);
    lv_obj_set_width(ui_Thickness3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness3, 40);
    lv_obj_set_y(ui_Thickness3, 0);
    lv_obj_set_align(ui_Thickness3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness3, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel4 = lv_obj_create(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessPanel4, 185);
    lv_obj_set_height(ui_ThicknessPanel4, 47);
    lv_obj_set_x(ui_ThicknessPanel4, 0);
    lv_obj_set_y(ui_ThicknessPanel4, 59);
    lv_obj_set_align(ui_ThicknessPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel4 = lv_label_create(ui_ThicknessPanel4);
    lv_obj_set_width(ui_ThicknessLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel4, -20);
    lv_obj_set_y(ui_ThicknessLabel4, 0);
    lv_obj_set_align(ui_ThicknessLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel4, "No.4");
    lv_obj_set_style_text_color(ui_ThicknessLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel4, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness4 = lv_label_create(ui_ThicknessPanel4);
    lv_obj_set_width(ui_Thickness4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness4, 40);
    lv_obj_set_y(ui_Thickness4, 0);
    lv_obj_set_align(ui_Thickness4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness4, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel5 = lv_obj_create(ui_ThicknessA);
    lv_obj_set_width(ui_ThicknessPanel5, 185);
    lv_obj_set_height(ui_ThicknessPanel5, 47);
    lv_obj_set_x(ui_ThicknessPanel5, 0);
    lv_obj_set_y(ui_ThicknessPanel5, 115);
    lv_obj_set_align(ui_ThicknessPanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel5 = lv_label_create(ui_ThicknessPanel5);
    lv_obj_set_width(ui_ThicknessLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel5, -20);
    lv_obj_set_y(ui_ThicknessLabel5, 0);
    lv_obj_set_align(ui_ThicknessLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel5, "No.5");
    lv_obj_set_style_text_color(ui_ThicknessLabel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel5, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness5 = lv_label_create(ui_ThicknessPanel5);
    lv_obj_set_width(ui_Thickness5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness5, 40);
    lv_obj_set_y(ui_Thickness5, 0);
    lv_obj_set_align(ui_Thickness5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness5, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessB = lv_obj_create(ui_ThicknessMainPanel);
    lv_obj_remove_style_all(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessB, 215);
    lv_obj_set_height(ui_ThicknessB, 306);
    lv_obj_set_x(ui_ThicknessB, 200);
    lv_obj_set_y(ui_ThicknessB, 17);
    lv_obj_set_align(ui_ThicknessB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessPanel6 = lv_obj_create(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessPanel6, 185);
    lv_obj_set_height(ui_ThicknessPanel6, 47);
    lv_obj_set_x(ui_ThicknessPanel6, 0);
    lv_obj_set_y(ui_ThicknessPanel6, -115);
    lv_obj_set_align(ui_ThicknessPanel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel6 = lv_label_create(ui_ThicknessPanel6);
    lv_obj_set_width(ui_ThicknessLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel6, -20);
    lv_obj_set_y(ui_ThicknessLabel6, 0);
    lv_obj_set_align(ui_ThicknessLabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel6, "No.6");
    lv_obj_set_style_text_color(ui_ThicknessLabel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel6, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness6 = lv_label_create(ui_ThicknessPanel6);
    lv_obj_set_width(ui_Thickness6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness6, 40);
    lv_obj_set_y(ui_Thickness6, 0);
    lv_obj_set_align(ui_Thickness6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness6, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel7 = lv_obj_create(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessPanel7, 185);
    lv_obj_set_height(ui_ThicknessPanel7, 47);
    lv_obj_set_x(ui_ThicknessPanel7, 0);
    lv_obj_set_y(ui_ThicknessPanel7, -57);
    lv_obj_set_align(ui_ThicknessPanel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel7 = lv_label_create(ui_ThicknessPanel7);
    lv_obj_set_width(ui_ThicknessLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel7, -20);
    lv_obj_set_y(ui_ThicknessLabel7, 0);
    lv_obj_set_align(ui_ThicknessLabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel7, "No.7");
    lv_obj_set_style_text_color(ui_ThicknessLabel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel7, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness7 = lv_label_create(ui_ThicknessPanel7);
    lv_obj_set_width(ui_Thickness7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness7, 40);
    lv_obj_set_y(ui_Thickness7, 0);
    lv_obj_set_align(ui_Thickness7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness7, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel8 = lv_obj_create(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessPanel8, 185);
    lv_obj_set_height(ui_ThicknessPanel8, 47);
    lv_obj_set_align(ui_ThicknessPanel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel8 = lv_label_create(ui_ThicknessPanel8);
    lv_obj_set_width(ui_ThicknessLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel8, -20);
    lv_obj_set_y(ui_ThicknessLabel8, 0);
    lv_obj_set_align(ui_ThicknessLabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel8, "No.8");
    lv_obj_set_style_text_color(ui_ThicknessLabel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel8, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel8, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel8, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness8 = lv_label_create(ui_ThicknessPanel8);
    lv_obj_set_width(ui_Thickness8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness8, 40);
    lv_obj_set_y(ui_Thickness8, 0);
    lv_obj_set_align(ui_Thickness8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness8, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness8, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel9 = lv_obj_create(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessPanel9, 185);
    lv_obj_set_height(ui_ThicknessPanel9, 47);
    lv_obj_set_x(ui_ThicknessPanel9, 0);
    lv_obj_set_y(ui_ThicknessPanel9, 59);
    lv_obj_set_align(ui_ThicknessPanel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel9 = lv_label_create(ui_ThicknessPanel9);
    lv_obj_set_width(ui_ThicknessLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel9, -20);
    lv_obj_set_y(ui_ThicknessLabel9, 0);
    lv_obj_set_align(ui_ThicknessLabel9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel9, "No.9");
    lv_obj_set_style_text_color(ui_ThicknessLabel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel9, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel9, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel9, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness9 = lv_label_create(ui_ThicknessPanel9);
    lv_obj_set_width(ui_Thickness9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness9, 40);
    lv_obj_set_y(ui_Thickness9, 0);
    lv_obj_set_align(ui_Thickness9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness9, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness9, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessPanel10 = lv_obj_create(ui_ThicknessB);
    lv_obj_set_width(ui_ThicknessPanel10, 185);
    lv_obj_set_height(ui_ThicknessPanel10, 47);
    lv_obj_set_x(ui_ThicknessPanel10, 0);
    lv_obj_set_y(ui_ThicknessPanel10, 115);
    lv_obj_set_align(ui_ThicknessPanel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessPanel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel10 = lv_label_create(ui_ThicknessPanel10);
    lv_obj_set_width(ui_ThicknessLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessLabel10, -20);
    lv_obj_set_y(ui_ThicknessLabel10, 0);
    lv_obj_set_align(ui_ThicknessLabel10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel10, "No.10");
    lv_obj_set_style_text_color(ui_ThicknessLabel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessLabel10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ThicknessLabel10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThicknessLabel10, lv_color_hex(0x0059FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThicknessLabel10, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThicknessLabel10, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThicknessLabel10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThicknessLabel10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thickness10 = lv_label_create(ui_ThicknessPanel10);
    lv_obj_set_width(ui_Thickness10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thickness10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thickness10, 40);
    lv_obj_set_y(ui_Thickness10, 0);
    lv_obj_set_align(ui_Thickness10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thickness10, "XX.XX");
    lv_obj_set_style_text_align(ui_Thickness10, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thickness10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelBtn = lv_btn_create(ui_ThicknessPage);
    lv_obj_set_width(ui_CancelBtn, 200);
    lv_obj_set_height(ui_CancelBtn, 50);
    lv_obj_set_x(ui_CancelBtn, -180);
    lv_obj_set_y(ui_CancelBtn, 199);
    lv_obj_set_align(ui_CancelBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CancelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelBtn, lv_color_hex(0x970000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CancelBtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CancelBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cancel = lv_label_create(ui_CancelBtn);
    lv_obj_set_width(ui_Cancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Cancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cancel, "Cancel");
    lv_obj_set_style_text_font(ui_Cancel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmBtn = lv_btn_create(ui_ThicknessPage);
    lv_obj_set_width(ui_ConfirmBtn, 200);
    lv_obj_set_height(ui_ConfirmBtn, 50);
    lv_obj_set_x(ui_ConfirmBtn, 180);
    lv_obj_set_y(ui_ConfirmBtn, 199);
    lv_obj_set_align(ui_ConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ConfirmBtn, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ConfirmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfirmBtn, lv_color_hex(0x004301), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ConfirmBtn, lv_color_hex(0x01C503), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfirmBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfirmBtn, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_ConfirmBtn, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_ConfirmBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Confirm = lv_label_create(ui_ConfirmBtn);
    lv_obj_set_width(ui_Confirm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Confirm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Confirm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Confirm, "Confirm");
    lv_obj_set_style_text_font(ui_Confirm, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardPanel = lv_obj_create(ui_ThicknessPage);
    lv_obj_set_width(ui_KeyboardPanel, 529);
    lv_obj_set_height(ui_KeyboardPanel, 297);
    lv_obj_set_x(ui_KeyboardPanel, -10);
    lv_obj_set_y(ui_KeyboardPanel, 90);
    lv_obj_set_align(ui_KeyboardPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_KeyboardPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_KeyboardPanel, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KeyboardPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_KeyboardPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_KeyboardPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessKeyboard = lv_keyboard_create(ui_KeyboardPanel);
    lv_keyboard_set_mode(ui_ThicknessKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_ThicknessKeyboard, 531);
    lv_obj_set_height(ui_ThicknessKeyboard, 231);
    lv_obj_set_x(ui_ThicknessKeyboard, -1);
    lv_obj_set_y(ui_ThicknessKeyboard, 30);
    lv_obj_set_align(ui_ThicknessKeyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ThicknessKeyboard, lv_color_hex(0xA4D0FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThicknessKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ThicknessKeyboard, &lv_font_montserrat_22, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_ThicknessValue = lv_textarea_create(ui_KeyboardPanel);
    lv_obj_set_width(ui_ThicknessValue, 490);
    lv_obj_set_height(ui_ThicknessValue, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_ThicknessValue, 0);
    lv_obj_set_y(ui_ThicknessValue, -117);
    lv_obj_set_align(ui_ThicknessValue, LV_ALIGN_CENTER);
    if("0123456789." == "") lv_textarea_set_accepted_chars(ui_ThicknessValue, NULL);
    else lv_textarea_set_accepted_chars(ui_ThicknessValue, "0123456789.");
    lv_textarea_set_max_length(ui_ThicknessValue, 5);
    lv_textarea_set_placeholder_text(ui_ThicknessValue, "Thickness...");
    lv_textarea_set_one_line(ui_ThicknessValue, true);
    lv_obj_set_style_text_font(ui_ThicknessValue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel2 = lv_obj_create(ui_ThicknessPage);
    lv_obj_set_width(ui_Panel2, 295);
    lv_obj_set_height(ui_Panel2, 57);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -209);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xE300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0xF1A4FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessTitleLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_ThicknessTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThicknessTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThicknessTitleLabel, "Thickness");
    lv_obj_set_style_text_color(ui_ThicknessTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThicknessTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThicknessTitleLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_ThicknessKeyboard, ui_ThicknessValue);
    lv_obj_add_event_cb(ui_ThicknessPage, ui_event_ThicknessPage, LV_EVENT_ALL, NULL);

}
