// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Weight

#include "../ui.h"

void ui_WeighingPage_screen_init(void)
{
    ui_WeighingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeighingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeightPanel1 = lv_obj_create(ui_WeighingPage);
    lv_obj_set_width(ui_WeightPanel1, 230);
    lv_obj_set_height(ui_WeightPanel1, 110);
    lv_obj_set_x(ui_WeightPanel1, -265);
    lv_obj_set_y(ui_WeightPanel1, -15);
    lv_obj_set_align(ui_WeightPanel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_WeightPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeightPanel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeightPanel1, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeightPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WeightPanel1, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WeightPanel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WeightPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WeightPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WeightPanel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WeightPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleWeight1 = lv_label_create(ui_WeightPanel1);
    lv_obj_set_width(ui_TitleWeight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleWeight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleWeight1, 0);
    lv_obj_set_y(ui_TitleWeight1, -57);
    lv_obj_set_align(ui_TitleWeight1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleWeight1, "Weight1");
    lv_obj_set_style_text_color(ui_TitleWeight1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleWeight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleWeight1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleWeight1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleWeight1, lv_color_hex(0x0069FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleWeight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TitleWeight1, lv_color_hex(0x408CFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TitleWeight1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleWeight1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleWeight1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleWeight1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleWeight1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight1 = lv_label_create(ui_WeightPanel1);
    lv_obj_set_width(ui_Weight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weight1, "XX.XXX");
    lv_obj_set_style_text_color(ui_Weight1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weight1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightPanel2 = lv_obj_create(ui_WeighingPage);
    lv_obj_set_width(ui_WeightPanel2, 230);
    lv_obj_set_height(ui_WeightPanel2, 110);
    lv_obj_set_x(ui_WeightPanel2, 0);
    lv_obj_set_y(ui_WeightPanel2, -15);
    lv_obj_set_align(ui_WeightPanel2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_WeightPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeightPanel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeightPanel2, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeightPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WeightPanel2, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WeightPanel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WeightPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WeightPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WeightPanel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WeightPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleWeight2 = lv_label_create(ui_WeightPanel2);
    lv_obj_set_width(ui_TitleWeight2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleWeight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleWeight2, 0);
    lv_obj_set_y(ui_TitleWeight2, -57);
    lv_obj_set_align(ui_TitleWeight2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleWeight2, "Weight2");
    lv_obj_set_style_text_color(ui_TitleWeight2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleWeight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleWeight2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleWeight2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleWeight2, lv_color_hex(0x0069FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleWeight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TitleWeight2, lv_color_hex(0x408CFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TitleWeight2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleWeight2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleWeight2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleWeight2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleWeight2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight2 = lv_label_create(ui_WeightPanel2);
    lv_obj_set_width(ui_Weight2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weight2, "XX.XXX");
    lv_obj_set_style_text_color(ui_Weight2, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weight2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AveragePanel = lv_obj_create(ui_WeighingPage);
    lv_obj_set_width(ui_AveragePanel, 230);
    lv_obj_set_height(ui_AveragePanel, 110);
    lv_obj_set_x(ui_AveragePanel, 256);
    lv_obj_set_y(ui_AveragePanel, -15);
    lv_obj_set_align(ui_AveragePanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_AveragePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AveragePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AveragePanel, lv_color_hex(0xFDCD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AveragePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AveragePanel, lv_color_hex(0xFBE37D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AveragePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AveragePanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AveragePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleAverage = lv_label_create(ui_AveragePanel);
    lv_obj_set_width(ui_TitleAverage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleAverage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleAverage, 0);
    lv_obj_set_y(ui_TitleAverage, -57);
    lv_obj_set_align(ui_TitleAverage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleAverage, "Average");
    lv_obj_set_style_text_color(ui_TitleAverage, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleAverage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleAverage, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitleAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitleAverage, lv_color_hex(0x0069FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleAverage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TitleAverage, lv_color_hex(0x408CFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TitleAverage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitleAverage, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleAverage, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleAverage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Average = lv_label_create(ui_AveragePanel);
    lv_obj_set_width(ui_Average, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Average, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Average, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Average, "XX.XXX");
    lv_obj_set_style_text_color(ui_Average, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Average, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Average, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightSetMainPanel = lv_obj_create(ui_WeighingPage);
    lv_obj_set_width(ui_WeightSetMainPanel, 765);
    lv_obj_set_height(ui_WeightSetMainPanel, 318);
    lv_obj_set_x(ui_WeightSetMainPanel, 0);
    lv_obj_set_y(ui_WeightSetMainPanel, -64);
    lv_obj_set_align(ui_WeightSetMainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeightSetMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_WeightSetMainPanel, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WeightSetMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WeightSetMainPanel, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WeightSetMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WeightSetMainPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WeightSetMainPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProductContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_ProductContainer);
    lv_obj_set_width(ui_ProductContainer, 358);
    lv_obj_set_height(ui_ProductContainer, 35);
    lv_obj_set_x(ui_ProductContainer, -175);
    lv_obj_set_y(ui_ProductContainer, -127);
    lv_obj_set_align(ui_ProductContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProductContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProductLabel = lv_label_create(ui_ProductContainer);
    lv_obj_set_width(ui_ProductLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProductLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProductLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ProductLabel, "Product name");
    lv_obj_set_style_text_font(ui_ProductLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveProductContainer = lv_obj_create(ui_ProductContainer);
    lv_obj_remove_style_all(ui_SlaveProductContainer);
    lv_obj_set_width(ui_SlaveProductContainer, 210);
    lv_obj_set_height(ui_SlaveProductContainer, 25);
    lv_obj_set_x(ui_SlaveProductContainer, 64);
    lv_obj_set_y(ui_SlaveProductContainer, 0);
    lv_obj_set_align(ui_SlaveProductContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveProductContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProductName = lv_label_create(ui_SlaveProductContainer);
    lv_obj_set_width(ui_ProductName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProductName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProductName, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ProductName, "XXXXXXXXXX");
    lv_obj_set_style_text_font(ui_ProductName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LotContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_LotContainer);
    lv_obj_set_width(ui_LotContainer, 358);
    lv_obj_set_height(ui_LotContainer, 35);
    lv_obj_set_x(ui_LotContainer, -175);
    lv_obj_set_y(ui_LotContainer, -99);
    lv_obj_set_align(ui_LotContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LotContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LotLabel = lv_label_create(ui_LotContainer);
    lv_obj_set_width(ui_LotLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LotLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LotLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LotLabel, "Lot No.");
    lv_obj_set_style_text_font(ui_LotLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveLotContainer = lv_obj_create(ui_LotContainer);
    lv_obj_remove_style_all(ui_SlaveLotContainer);
    lv_obj_set_width(ui_SlaveLotContainer, 210);
    lv_obj_set_height(ui_SlaveLotContainer, 25);
    lv_obj_set_align(ui_SlaveLotContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveLotContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LotNumber = lv_label_create(ui_SlaveLotContainer);
    lv_obj_set_width(ui_LotNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LotNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LotNumber, 1);
    lv_obj_set_y(ui_LotNumber, 1);
    lv_obj_set_align(ui_LotNumber, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LotNumber, "XXXXXXX");
    lv_obj_set_style_text_font(ui_LotNumber, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_BalanceContainer);
    lv_obj_set_width(ui_BalanceContainer, 358);
    lv_obj_set_height(ui_BalanceContainer, 35);
    lv_obj_set_x(ui_BalanceContainer, -175);
    lv_obj_set_y(ui_BalanceContainer, -71);
    lv_obj_set_align(ui_BalanceContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BalanceContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BalanceLabel = lv_label_create(ui_BalanceContainer);
    lv_obj_set_width(ui_BalanceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BalanceLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BalanceLabel, "Balance No.");
    lv_obj_set_style_text_font(ui_BalanceLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveBalanceContainer = lv_obj_create(ui_BalanceContainer);
    lv_obj_remove_style_all(ui_SlaveBalanceContainer);
    lv_obj_set_width(ui_SlaveBalanceContainer, 210);
    lv_obj_set_height(ui_SlaveBalanceContainer, 25);
    lv_obj_set_x(ui_SlaveBalanceContainer, 42);
    lv_obj_set_y(ui_SlaveBalanceContainer, 0);
    lv_obj_set_align(ui_SlaveBalanceContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveBalanceContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BalanceID = lv_label_create(ui_SlaveBalanceContainer);
    lv_obj_set_width(ui_BalanceID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BalanceID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BalanceID, "XXXXXXX");
    lv_obj_set_style_text_font(ui_BalanceID, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabletIDContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_TabletIDContainer);
    lv_obj_set_width(ui_TabletIDContainer, 358);
    lv_obj_set_height(ui_TabletIDContainer, 35);
    lv_obj_set_x(ui_TabletIDContainer, -175);
    lv_obj_set_y(ui_TabletIDContainer, -43);
    lv_obj_set_align(ui_TabletIDContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabletIDContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabletIDLabel = lv_label_create(ui_TabletIDContainer);
    lv_obj_set_width(ui_TabletIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TabletIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TabletIDLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TabletIDLabel, "Tableting No.");
    lv_obj_set_style_text_font(ui_TabletIDLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveTabletIDContainer = lv_obj_create(ui_TabletIDContainer);
    lv_obj_remove_style_all(ui_SlaveTabletIDContainer);
    lv_obj_set_width(ui_SlaveTabletIDContainer, 210);
    lv_obj_set_height(ui_SlaveTabletIDContainer, 25);
    lv_obj_set_x(ui_SlaveTabletIDContainer, 54);
    lv_obj_set_y(ui_SlaveTabletIDContainer, 0);
    lv_obj_set_align(ui_SlaveTabletIDContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveTabletIDContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabletID = lv_label_create(ui_SlaveTabletIDContainer);
    lv_obj_set_width(ui_TabletID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TabletID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TabletID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TabletID, "XXX");
    lv_obj_set_style_text_font(ui_TabletID, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight10sContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_Weight10sContainer);
    lv_obj_set_width(ui_Weight10sContainer, 358);
    lv_obj_set_height(ui_Weight10sContainer, 35);
    lv_obj_set_x(ui_Weight10sContainer, -175);
    lv_obj_set_y(ui_Weight10sContainer, -14);
    lv_obj_set_align(ui_Weight10sContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weight10sContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weight10sLabel = lv_label_create(ui_Weight10sContainer);
    lv_obj_set_width(ui_Weight10sLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10sLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight10sLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Weight10sLabel, "Mean weight (10's)");
    lv_obj_set_style_text_font(ui_Weight10sLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveWeight10sContainer = lv_obj_create(ui_Weight10sContainer);
    lv_obj_remove_style_all(ui_SlaveWeight10sContainer);
    lv_obj_set_width(ui_SlaveWeight10sContainer, 65);
    lv_obj_set_height(ui_SlaveWeight10sContainer, 25);
    lv_obj_set_x(ui_SlaveWeight10sContainer, 29);
    lv_obj_set_y(ui_SlaveWeight10sContainer, 0);
    lv_obj_set_align(ui_SlaveWeight10sContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveWeight10sContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weight10s = lv_label_create(ui_SlaveWeight10sContainer);
    lv_obj_set_width(ui_Weight10s, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10s, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight10s, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Weight10s, "XX.XXX");
    lv_obj_set_style_text_font(ui_Weight10s, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight10sUnit = lv_label_create(ui_Weight10sContainer);
    lv_obj_set_width(ui_Weight10sUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10sUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weight10sUnit, 72);
    lv_obj_set_y(ui_Weight10sUnit, -1);
    lv_obj_set_align(ui_Weight10sUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weight10sUnit, "g.");
    lv_obj_set_style_text_font(ui_Weight10sUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight10sPerContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_Weight10sPerContainer);
    lv_obj_set_width(ui_Weight10sPerContainer, 358);
    lv_obj_set_height(ui_Weight10sPerContainer, 35);
    lv_obj_set_x(ui_Weight10sPerContainer, -175);
    lv_obj_set_y(ui_Weight10sPerContainer, 15);
    lv_obj_set_align(ui_Weight10sPerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weight10sPerContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weight10sPerLabel = lv_label_create(ui_Weight10sPerContainer);
    lv_obj_set_width(ui_Weight10sPerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10sPerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight10sPerLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Weight10sPerLabel, "% Weight variation (10's)");
    lv_obj_set_style_text_font(ui_Weight10sPerLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveWeight10sPerContainer = lv_obj_create(ui_Weight10sPerContainer);
    lv_obj_remove_style_all(ui_SlaveWeight10sPerContainer);
    lv_obj_set_width(ui_SlaveWeight10sPerContainer, 55);
    lv_obj_set_height(ui_SlaveWeight10sPerContainer, 25);
    lv_obj_set_x(ui_SlaveWeight10sPerContainer, 74);
    lv_obj_set_y(ui_SlaveWeight10sPerContainer, 0);
    lv_obj_set_align(ui_SlaveWeight10sPerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveWeight10sPerContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weight10sPer = lv_label_create(ui_SlaveWeight10sPerContainer);
    lv_obj_set_width(ui_Weight10sPer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10sPer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weight10sPer, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Weight10sPer, "XX.XX");
    lv_obj_set_style_text_font(ui_Weight10sPer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weight10sPerUnit = lv_label_create(ui_Weight10sPerContainer);
    lv_obj_set_width(ui_Weight10sPerUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weight10sPerUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weight10sPerUnit, 108);
    lv_obj_set_y(ui_Weight10sPerUnit, 0);
    lv_obj_set_align(ui_Weight10sPerUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weight10sPerUnit, "%");
    lv_obj_set_style_text_font(ui_Weight10sPerUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeanWeightInhouseContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_MeanWeightInhouseContainer);
    lv_obj_set_width(ui_MeanWeightInhouseContainer, 526);
    lv_obj_set_height(ui_MeanWeightInhouseContainer, 35);
    lv_obj_set_x(ui_MeanWeightInhouseContainer, -90);
    lv_obj_set_y(ui_MeanWeightInhouseContainer, 43);
    lv_obj_set_align(ui_MeanWeightInhouseContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MeanWeightInhouseContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeanWeightInhouseLabel = lv_label_create(ui_MeanWeightInhouseContainer);
    lv_obj_set_width(ui_MeanWeightInhouseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeanWeightInhouseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeanWeightInhouseLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MeanWeightInhouseLabel, "Range of mean weight (in-house)");
    lv_obj_set_style_text_font(ui_MeanWeightInhouseLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveMeanWeightInhouseContainer = lv_obj_create(ui_MeanWeightInhouseContainer);
    lv_obj_remove_style_all(ui_SlaveMeanWeightInhouseContainer);
    lv_obj_set_width(ui_SlaveMeanWeightInhouseContainer, 145);
    lv_obj_set_height(ui_SlaveMeanWeightInhouseContainer, 25);
    lv_obj_set_x(ui_SlaveMeanWeightInhouseContainer, 118);
    lv_obj_set_y(ui_SlaveMeanWeightInhouseContainer, 0);
    lv_obj_set_align(ui_SlaveMeanWeightInhouseContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveMeanWeightInhouseContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeightInhouseMin = lv_label_create(ui_SlaveMeanWeightInhouseContainer);
    lv_obj_set_width(ui_WeightInhouseMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightInhouseMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightInhouseMin, -38);
    lv_obj_set_y(ui_WeightInhouseMin, 0);
    lv_obj_set_align(ui_WeightInhouseMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeightInhouseMin, "XX.XXX");
    lv_obj_set_style_text_font(ui_WeightInhouseMin, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dash = lv_label_create(ui_SlaveMeanWeightInhouseContainer);
    lv_obj_set_width(ui_dash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dash, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dash, "-");
    lv_obj_set_style_text_font(ui_dash, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightInhouseMax = lv_label_create(ui_SlaveMeanWeightInhouseContainer);
    lv_obj_set_width(ui_WeightInhouseMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightInhouseMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightInhouseMax, 38);
    lv_obj_set_y(ui_WeightInhouseMax, 0);
    lv_obj_set_align(ui_WeightInhouseMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeightInhouseMax, "XX.XXX");
    lv_obj_set_style_text_font(ui_WeightInhouseMax, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeanWeightInhouseUnit = lv_label_create(ui_MeanWeightInhouseContainer);
    lv_obj_set_width(ui_MeanWeightInhouseUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeanWeightInhouseUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeanWeightInhouseUnit, 199);
    lv_obj_set_y(ui_MeanWeightInhouseUnit, 0);
    lv_obj_set_align(ui_MeanWeightInhouseUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeanWeightInhouseUnit, "g.");
    lv_obj_set_style_text_font(ui_MeanWeightInhouseUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeanWeightREGContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_MeanWeightREGContainer);
    lv_obj_set_width(ui_MeanWeightREGContainer, 526);
    lv_obj_set_height(ui_MeanWeightREGContainer, 35);
    lv_obj_set_x(ui_MeanWeightREGContainer, -90);
    lv_obj_set_y(ui_MeanWeightREGContainer, 72);
    lv_obj_set_align(ui_MeanWeightREGContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MeanWeightREGContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeanWeightREGLabel = lv_label_create(ui_MeanWeightREGContainer);
    lv_obj_set_width(ui_MeanWeightREGLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeanWeightREGLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeanWeightREGLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MeanWeightREGLabel, "Range of mean weight (Reg.)");
    lv_obj_set_style_text_font(ui_MeanWeightREGLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveMeanWeightREGContainer = lv_obj_create(ui_MeanWeightREGContainer);
    lv_obj_remove_style_all(ui_SlaveMeanWeightREGContainer);
    lv_obj_set_width(ui_SlaveMeanWeightREGContainer, 147);
    lv_obj_set_height(ui_SlaveMeanWeightREGContainer, 25);
    lv_obj_set_x(ui_SlaveMeanWeightREGContainer, 79);
    lv_obj_set_y(ui_SlaveMeanWeightREGContainer, 0);
    lv_obj_set_align(ui_SlaveMeanWeightREGContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveMeanWeightREGContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeightRegMin = lv_label_create(ui_SlaveMeanWeightREGContainer);
    lv_obj_set_width(ui_WeightRegMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightRegMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightRegMin, -38);
    lv_obj_set_y(ui_WeightRegMin, 0);
    lv_obj_set_align(ui_WeightRegMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeightRegMin, "XX.XXX");
    lv_obj_set_style_text_font(ui_WeightRegMin, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dash2 = lv_label_create(ui_SlaveMeanWeightREGContainer);
    lv_obj_set_width(ui_dash2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dash2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dash2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dash2, "-");
    lv_obj_set_style_text_font(ui_dash2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightRegMax = lv_label_create(ui_SlaveMeanWeightREGContainer);
    lv_obj_set_width(ui_WeightRegMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightRegMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightRegMax, 38);
    lv_obj_set_y(ui_WeightRegMax, 0);
    lv_obj_set_align(ui_WeightRegMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeightRegMax, "XX.XXX");
    lv_obj_set_style_text_font(ui_WeightRegMax, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeanWeightREGUnit = lv_label_create(ui_MeanWeightREGContainer);
    lv_obj_set_width(ui_MeanWeightREGUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeanWeightREGUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeanWeightREGUnit, 160);
    lv_obj_set_y(ui_MeanWeightREGUnit, 0);
    lv_obj_set_align(ui_MeanWeightREGUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeanWeightREGUnit, "g.");
    lv_obj_set_style_text_font(ui_MeanWeightREGUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessContainer = lv_obj_create(ui_WeightSetMainPanel);
    lv_obj_remove_style_all(ui_ThicknessContainer);
    lv_obj_set_width(ui_ThicknessContainer, 358);
    lv_obj_set_height(ui_ThicknessContainer, 35);
    lv_obj_set_x(ui_ThicknessContainer, -173);
    lv_obj_set_y(ui_ThicknessContainer, 101);
    lv_obj_set_align(ui_ThicknessContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThicknessContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessLabel = lv_label_create(ui_ThicknessContainer);
    lv_obj_set_width(ui_ThicknessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThicknessLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ThicknessLabel, "Thickness");
    lv_obj_set_style_text_font(ui_ThicknessLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveThicknessContainer = lv_obj_create(ui_ThicknessContainer);
    lv_obj_remove_style_all(ui_SlaveThicknessContainer);
    lv_obj_set_width(ui_SlaveThicknessContainer, 114);
    lv_obj_set_height(ui_SlaveThicknessContainer, 25);
    lv_obj_set_x(ui_SlaveThicknessContainer, -26);
    lv_obj_set_y(ui_SlaveThicknessContainer, 0);
    lv_obj_set_align(ui_SlaveThicknessContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SlaveThicknessContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThicknessMin = lv_label_create(ui_SlaveThicknessContainer);
    lv_obj_set_width(ui_ThicknessMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessMin, -30);
    lv_obj_set_y(ui_ThicknessMin, 0);
    lv_obj_set_align(ui_ThicknessMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThicknessMin, "XX.XX");
    lv_obj_set_style_text_font(ui_ThicknessMin, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThicknessMax = lv_label_create(ui_SlaveThicknessContainer);
    lv_obj_set_width(ui_ThicknessMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThicknessMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThicknessMax, 30);
    lv_obj_set_y(ui_ThicknessMax, 0);
    lv_obj_set_align(ui_ThicknessMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThicknessMax, "XX.XX");
    lv_obj_set_style_text_font(ui_ThicknessMax, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dash3 = lv_label_create(ui_SlaveThicknessContainer);
    lv_obj_set_width(ui_dash3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dash3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dash3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dash3, "-");
    lv_obj_set_style_text_font(ui_dash3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeanWeightREGUnit1 = lv_label_create(ui_ThicknessContainer);
    lv_obj_set_width(ui_MeanWeightREGUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeanWeightREGUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeanWeightREGUnit1, 55);
    lv_obj_set_y(ui_MeanWeightREGUnit1, 0);
    lv_obj_set_align(ui_MeanWeightREGUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeanWeightREGUnit1, "mm.");
    lv_obj_set_style_text_font(ui_MeanWeightREGUnit1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateSettingBtn = lv_btn_create(ui_WeightSetMainPanel);
    lv_obj_set_width(ui_UpdateSettingBtn, 125);
    lv_obj_set_height(ui_UpdateSettingBtn, 51);
    lv_obj_set_x(ui_UpdateSettingBtn, 305);
    lv_obj_set_y(ui_UpdateSettingBtn, -120);
    lv_obj_set_align(ui_UpdateSettingBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateSettingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UpdateSettingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UpdateSettingBtn, lv_color_hex(0x004301), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UpdateSettingBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_UpdateSettingBtn, lv_color_hex(0x01C503), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_UpdateSettingBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateSettingLabel = lv_label_create(ui_UpdateSettingBtn);
    lv_obj_set_width(ui_UpdateSettingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpdateSettingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UpdateSettingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpdateSettingLabel, "UPDATE");
    lv_obj_set_style_text_font(ui_UpdateSettingLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClearSettingBtn = lv_btn_create(ui_WeightSetMainPanel);
    lv_obj_set_width(ui_ClearSettingBtn, 125);
    lv_obj_set_height(ui_ClearSettingBtn, 51);
    lv_obj_set_x(ui_ClearSettingBtn, 305);
    lv_obj_set_y(ui_ClearSettingBtn, -55);
    lv_obj_set_align(ui_ClearSettingBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClearSettingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ClearSettingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ClearSettingBtn, lv_color_hex(0x970000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClearSettingBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ClearSettingBtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ClearSettingBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClearSettingLabel = lv_label_create(ui_ClearSettingBtn);
    lv_obj_set_width(ui_ClearSettingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClearSettingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ClearSettingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClearSettingLabel, "CLEAR");
    lv_obj_set_style_text_font(ui_ClearSettingLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WeighingPage, ui_event_WeighingPage, LV_EVENT_ALL, NULL);

}
